### ISSUE TITLE
Jumping pinned element

### ISSUE THREAD

**Issue by gornypiotr** [janpaepke/ScrollMagic#10]
Hi
firstly I'd like to thank you for a great job with this library! I've tried a few other libraries and found yours the easiest and most intuitive to use. I'm building a website, where I've got a chemical apparatus in SVG with simple animation - just revealing and hiding particular elements, while scrolling.
I've pinned my SVG and I do the animation on the scroll, having the SVG in the middle of a page. Unfortunately what I observe is that in Chrome, IE11 and Opera it works great, but in Firefox the pinned element jumps while scrolling - it moves up and down by a few pixels. It's very likely I do something wrong, but I would appreciate if you could point me to my mistake. Or maybe there's something with the library...
Please have a look at this page: http://magdalenakrzys.pl/beta/ if you don't mind helping me. Please bear in mind that the page is still being developed, so there might be some flaws :-)
Thank you in advance.

**Comment by hatchbee** [comment]
I am facing this issue on Chrome with ScrollMagic v2.0.5

It is actually weird, that the issue is only on two of four pinned element.

**Comment by janpaepke** [comment]
@hatchbee please post as a separate issue, with example

**Comment by maxedison** [comment]
@hatchbee -- are the elements that are experiencing the jumping inside a container with top padding? I just experienced this with something like:

<main>
  <h2>Pin this!</h2>
</main>

And <main> had padding-top: 15vh. By removing that padding from <main> and adding it to <h2>, the problem was solved. Perhaps you are experiencing something similar.

**Comment by hatchbee** [comment]
@maxedison I couldn't remember what was the actual issue was, but I did re-worked on the pinning thing and the issue was resolved. Not sure why it was flickering and jumping the element when the pinning starts.

**Comment by smWtf** [comment]
Not sure if problem I experienced has the same roots as the one reported in OP, but in my case pinned element still jumps sometimes if I move out of the scene and then scroll back in. 

It happens because currently `padding` properties of pin spacer are not being recalculated when element is getting unpinned. This is easily noticeable if we move out of the scene by changing scroll position in big steps and then move back in smoothly scrolling container this time. 

When we jump past the start/end point of the scene, element is getting unpinned correctly, but its container stucks with offset from the last time scene was updated while it was active. Once we start moving back and enter the scene again, Scrollmagic recalulates styles for pined element and one of the paddings getting changed to 0, resulting in element make a significant jump to the position where it's supposed to be.

This is the guilty part

	if (_state === SCENE_STATE_AFTER && parseFloat(_util.css(_pinOptions.spacer, "padding-top")) === 0) {
		change = true; // if in after state but havent updated spacer yet (jumped past pin)
	} else if (_state === SCENE_STATE_BEFORE && parseFloat(_util.css(_pinOptions.spacer, "padding-bottom")) === 0) { // before
		change = true; // jumped past fixed state upward direction
	}

We also need to make sure here that `padding-bottom` was set to 0 if we jumped past the end of the scene and `padding-top` was set to 0 if jumped past the start of it. But considering that whole condition is only being executed once per entering/leaving scene (at least it was so in my case)  whole thing may be redundant and can be replaced with `change = true;`

Here's a pull request with a fix. #443

**Comment by sanvision** [comment]
I am facing issue in chrome on mac while scrolling. If the cursor position is on top of the screen the scrolling stops working. Can someone help me fixing the issue? Thanks in advance. url of my website - http://jproductions.in/

**Comment by MatSchaeff** [comment]
@smWtf I'm facing the same issue in chrome on mac : "pinned element still jumps sometimes if I move out of the scene and then scroll back in."
Except that I dont use pin but tween (for parallax scrolling). You seem to have a good understanding of the code, do you know how i could apply your fix to tween ?

**Comment by lukedohner** [comment]
I have found a hacky solution. Animating a larger background svg with svg object on top of the BG. Everthing is animated in a gsap timeline. 
If I have a time in the timeline without movement then start a movement most everything jumps.
In other word if nothing on the timeline stop be cause of a time gap a jump happens on the movement restart.

My solution was to have a little object animate throughout the entire timeline. My timeline has a duration of about 90 sec. The below tween continues even longer that the actual relevant animation.

tl_mine.to(keepmoving, 140, {css: {x: 2}}, '0');

worked for me.
