### ISSUE TITLE
Overlapping Pins

### ISSUE THREAD

**Issue by etaheri** [janpaepke/ScrollMagic#120]
Thanks for an awesome plugin!

I am having trouble achieving the desired effect however.  I want to pin an item for a duration and in the meantime have an another item scroll and pin on top of the previous item. After being pinned together for a period of time they would scroll away together.

My project currently pins for the duration set and the next item waits for that duration to begin to scroll and pin. 

Any help would be appreciated!

**Comment by sarahelizabeth** [comment]
How did you fix this problem using "pushFollowers"? It doesn't seem to work for me. I created an array of timelines which I am passing to a single scene in order to create navigation elements for each timeline, but I want these animations to happen over an image that is pinned for the duration of the scene. Do you have any tips? Thanks!

**Comment by janpaepke** [comment]
Hi Sarah,
please follow the [support guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md), create a jsfiddle and post a new issue. We'll gladly help you then.
