### ISSUE TITLE
"Error calling method 'setTween()' [...]" with v1.2.1

### ISSUE THREAD

**Issue by wrthwhl** [janpaepke/ScrollMagic#182]
Hi

I'm having an issue with the latest (1.2.1) version of the ingenious ScrollMagic. 

Following my JS...

``` javascript
var controller = new ScrollMagic({loglevel:3});
var tween = TweenMax.to(".panel.welcome", 0.5, {backgroundColor: "green", scale: 2.5});
var scene = new ScrollScene({triggerElement: "#panels", loglevel: 3})
                                .setTween(tween)
                                .addTo(controller);
```

...resulting in the following console-log:

> 21:28:16:307 (ScrollMagic) -> added new ScrollMagic controller **(vundefined)**
> 21:28:16:314 (ScrollScene) -> **ERROR calling method 'setTween()': Supplied argument is not a valid >TweenObject**
> 21:28:16:314 (ScrollScene) -> added tween
> 21:28:16:316 (ScrollScene) -> added ScrollScene to controller
> 21:28:16:316 (ScrollMagic) -> added Scene (1 total)
> 21:28:16:346 (ScrollMagic) -> updating Scene 1/1 (1 total)
> 21:28:16:347 (ScrollScene) -> event fired: update -> Object {startPos: -535, endPos: -535, scrollPos: 0} 
> 21:28:16:349 (ScrollScene) -> event fired: enter -> Object {progress: 1, state: "DURING", scrollDirection: "PAUSED"}
> 21:28:16:350 (ScrollScene) -> event fired: start -> Object {progress: 1, state: "DURING", scrollDirection: "PAUSED"}
> 21:28:16:351 (ScrollScene) -> event fired: progress -> Object {progress: 1, state: "DURING", scrollDirection: "PAUSED"} 

Thing is that if I go with version 1.0.9 the error disappears. With version 1.0.9 for the core and the latest (v1.2.1) debug extension I get the following Uncaught Type Error:

> 21:49:48:229 (ScrollScene) -> added tween
> 21:49:48:235 (ScrollScene) -> added ScrollScene to controller
> **Uncaught TypeError: undefined is not a function
> ScrollScene.updateIndicators
> ScrollScene.addIndicators
> (anonymous function)
> j 
> k.fireWith
> m.extend.ready
> J**
> 21:49:48:261 (ScrollScene) -> event fired: update -> Object {startPos: 0, endPos: 7380, scrollPos: 0} 

I hope this of any use.

Thank you heaps for ScrollMagic. I'm a huge fan.

Cheers
Marco

**Comment by drjorgepolanco** [comment]
So what should be the correct order? I am trying to replicate:
http://janpaepke.github.io/ScrollMagic/examples/advanced/parallax_sections.html

And I keep getting "Uncaught TypeError: (intermediate value).setTween is not a function".

This are my cdns in this exact order (removed <script> to show cleaner)
"https://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js"
"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/ScrollMagic.min.js"
"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/debug.addIndicators.min.js"

The code is the exact one copied and pasted from the source of the example link.

**Comment by famicomboy** [comment]
I'm getting this issue as well. I'm making a single page app with Webpack and Angular.  Currently using ScrollMagic 2.0.5, GSAP 1.18.2. 

Setup of my code: All the page routes are broken up into chunks to allow conditional loading of the site. I mention this because it's making working with 3rd party frameworks like this a bit more complicated to work with. Anyway, adding in the correct WP aliases (from [this comment](https://github.com/janpaepke/ScrollMagic/issues/324#issuecomment-161263064)) I finally got the debug indicators working. However, on trying to add a GSAP tween via setTween() I get the same error as the OP. 
`ScrollMagic.js:261721:34:56:350 (ScrollMagic.Scene) -> (animation.gsap) -> ERROR calling method 'setTween()': Supplied argument is not a valid TweenObjectScrollMagic._util.U.log @ ScrollMagic.js:2617log._log @ ScrollMagic.js:1212log @ animation.gsap.js:112Scene.setTween @ animation.gsap.js:225link @ scrollmagic-scene.directive.js:68(anonymous function) @ angular.js:9486invokeLinkFn @ angular.js:9492nodeLinkFn @ angular.js:8978compositeLinkFn @ angular.js:8226compositeLinkFn @ angular.js:8229publicLinkFn @ angular.js:8106(anonymous function) @ angular.js:8447boundTranscludeFn @ angular.js:8244controllersBoundTransclude @ angular.js:9020ngRepeatAction @ angular.js:28571$watchCollectionAction @ angular.js:16527Scope.$digest @ angular.js:16664(anonymous function) @ angular.js:16859completeOutstandingRequest @ angular.js:5804(anonymous function) @ angular.js:6081
scrollmagic-scene.directive.js:33scrollmagic directive link`

I've confirmed that the tween itself does run without adding it to ScrollMagic, so I doubt that's the issue. I wonder if it has something to do with gsap not returning a global TweenMax variable when I require it. This is how I call a tween: 
`var gsap = require('TweenMax'); 

module.exports = function() {
  var tween = gsap.TweenMax.to(el, duration, vars.....)};
}`

I look at the animation.gsap.js plugin and it's expecting "TweenMax" to just be available, but when I log out the "TweenMax" variable, it's returning the wrapper "gsap" object, so it has the easing functions, TweenMax class instance, etc, instead of the "to", "from", functions. I'm super new to this require world so I may just be completely misunderstanding how to load certain packages like this.

For reference, here's the module I'm trying to use this in: (being used as an Angular directive)
`'use strict';

var $ = require('jquery');

var gsap = require('TweenMax');
var TweenMax = gsap.TweenMax;
var TimelineMax = gsap.TimelineMax; //require('TimelineMax');
var ScrollMagic = require('ScrollMagic');
require('animation.gsap');
require('debug.addIndicators');
var template = require('templates/partials/content-slide-item.html');

module.exports = function() {
    return {
        restrict: 'A',
        link: function(scope, element, attrs) {
            var tween = TweenMax.to($(element).find(".title"), 1.0, {opacity: 0, repeat: 1000, yoyo: true});
            var controller = scope.controller;

            new ScrollMagic.Scene({
                duration: 1000,
                triggerElement: $(element).find('.sticky-trigger')[0]
            })
                .addIndicators()
                .setTween(tween)
                .addTo(controller);


        },
        template: template,
        scope: {
            data: '=',
            controller: '='
        }
    }
};
`

**Comment by krnlde** [comment]
@famicomboy did you take care of the AMD loading style? E.g. Require.js or System.js or browserify.

**Comment by famicomboy** [comment]
I'm a little unsure on that. I see that scrollmagic itself uses the define() method that webpack is looking for, but other than that I'm just using the require() method to load it.

**Comment by famicomboy** [comment]
Sorry everyone, I figured out my issue was unrelated to ScrollMagic. I apologize, this probably should've been a Stack Overflow post but I saw that this issue was the same error I was getting so thought it was better to put here.

**Comment by krnlde** [comment]
Could you still provide some insights for others who get caught by the same mistake?

**Comment by famicomboy** [comment]
The problem is I started out with [this yeoman generator](https://github.com/karolaltamirano/generator-angular-webpack) which installed a loader for GSAP files:
`"animation.gsap": 'scrollmagic/scrollmagic/uncompressed/plugins/animation.gsap.js',`

This was wrapping the module up in a container, making the TweenMax, TimelineMax etc variables inaccessible when loaded with require(); Disabling this loader made the dependent variables accessible to the animation plugin.
