### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by reggi** [janpaepke/ScrollMagic#208]
I published to npm

https://www.npmjs.org/package/scrollmagic

made pr to lowercase pakage name

https://github.com/janpaepke/ScrollMagic/pull/207

give me your npm handle and I'll add you!!!!

**Comment by ronnyamarante** [comment]
@janpaepke, i never see more poor answer. This software is under GPL license? Why you dont create your license? Really? I maybe suggest to add "non-official distribution" and problem solved.

**Comment by johnfmorton** [comment]
(jaw dropped)

**Comment by krnlde** [comment]
Why so offended, Ronny?

**Comment by ronnyamarante** [comment]
Because GPL or MIT license don't represent this project. 
"Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, **publish**, **distribute**, sublicense, and/or sell copies of the Software".   I believe in a better community...

**Comment by krnlde** [comment]
> I believe in a better community

If you are looking for a community that likes to debate on principles rather than actually helping people then sure, believe in it. You'll find your way I guess.

Thanks for requoting the GPL by the way. That makes it easier for everyone in this issue to understand what you're trying to proof.

So please rather than ranting on an actually pretty popular and successful project - which indeed is *free* and moreover free to "... use, copy, modify, merge, publish, distribute, sublicense ..." - you could  at least start contributing to it by improving its code and maybe *then* point out these kinds of flaws. You might even be able to put that on your [achievement list](ronnyamarante/achievements-list) later and show the world what a generous guy you are (if you first improved that code a little) or spend some time on [floppy bird](ronnyamarante/floppybird) and calm down a bit since your [Contribution Activity](https://github.com/ronnyamarante?tab=activity) quotes that you're actually not a "that active" coder. Work on that.

Jan just stated that he'd have done the publication himself rather than now sharding the whole project over many maintainers - eventually stopping to update their npm packages. He never forbade it.

And by "publish, distribute, sublicense" the GPL likely refers to modified versions of the said code and not the original one, but I guess at least this is discussable.

</rant>

Be thankful for every code you can use for free (that means no money and no other obligations).

**Comment by ronnyamarante** [comment]
@krnlde Sorry, but this quote is about MIT License and not GPL, work on that too..  I don't complain about the project but the request to remove the npm. It didn't make any sense. If someone publishes a copy of the project, is intended to help other people, ask to put "non-official project" wouldn't hurt anyone. You contribute to this project? ... If you understand how licenses helped, maybe youd understand.

**Comment by krnlde** [comment]
Still an advocate. Still hating. Still bad english. You've learned nothing. Kthxbye.

**Comment by reggi** [comment]
@krnlde you have a couple of typos:

> Thanks for requoting the GPL by the way. That makes it easier for everyone in this issue to understand what you're trying to proof.

"prove" not "proof"

> Be thankful for every code you can use for free (that means no money and no other obligations). Thinks like this are too rare in the world and should be appreciated a bit more. So also work on that.

"Things" not "Thinks"

Pointing out and chastising @ronnyamarante for his "bad english" is not only low, it's ironic. It's also completely off topic to bring up @ronnyamarante's github contribution history, activity, or achievement list.

@ronnyamarante Has a point, the license does state that I can and anyone can publish, and if the project contributors really wan't to prevent that perhaps the licence should be changed.

I respect @janpaepke wishes to have it removed from NPM. 

For those who want to use it with a browser-based node building system like [browserify](http://browserify.org/), [systemjs](https://github.com/systemjs/systemjs), [webpack](http://webpack.github.io/) via NPM, there's always:

 ```bash
npm i janpaepke/ScrollMagic
```

Thanks to @janpaepke, @johnpolacek, @francismakes, @gagarine, @aaronjensen, @slice-beans, @softvar, @zeevl, @masudo, @gion, @blackxored, @swalkinshaw, @kevinhamiltonsmith, and @lucanos for contributing to this open source project. I have much respect for all of you! :rainbow: :heart: :+1: :smile: :rocket: :full_moon:

**Comment by ronnyamarante** [comment]
:+1:

**Comment by janpaepke** [comment]
Hi guys,

I feel like I have to chime in here...

It started of by ronny stating that he'd "never seen more a poor answer".
Really? In all the full-of-flamers-and-wise-guys internet you've never seen even one? Even though I tried to be very polite and understanding? Wow you must really move around in the classy parts of the net.

Sarcasm aside:

There are reasons behind why I didn't want to have it published, which I borderline touched in the initial answer, but there are more.
Let me elaborate:

I stongly believe in open source and I do stand behind the license allowing people to publish it.
In this case though, there was no change to the code itself, it was the original package, so it should be decided by the package maintainers and contributors, when and where to publish it.
I would have NOTHING against someone publishing his fork or something.
The reason is that it would then be published as `scrollmagic-somefork` or something else.
If poeple use that as a dependency they are well aware of it being a version published and maintained by whoever forked it.

Once the package published as `scrollmagic` and people start adding it as a dependency there's no going back. Adding it to npm without even modifying the package.json is definitely not the right way to go.
It can cause problems like we now have with bower, where it is published as `ScrollMagic`, where as the name convention states it should be `scrollmagic`. Now if I want to change that all packages depending on it will fail.

It's also important to point out that I never forbade @reggi to publish it, as that would truly be against the license. I asked him to take it off because I felt it wasn't ready yet, again in the spirit of community.

Bottom line:
Publishing the package requires a lot of thought and all I wanted was exactly that.
Publishing it before it's ready or optimized is actually against the benefit of the community.

So before publishing it discussions by the community should take place, deciding how best to aproach it.
This is exactly what happened btw. And that's the power open source in my opinion.
So @ronnyamarante I'm sure you see I also believe in a better community, as community is exactly the power of open source. But this also means things should be discussed and decided as a community having in its own interest.

As I said I prepared publishing to NPM for ScrollMagic 2.0 and I have made the appropriate changes to the package.json: http://www.mergely.com/DAgzwVDr/

Finally, if I have offended you with my initial answer, @reggi I do apologize – it was not my intention.
I hope it is clear that I had and have the benefit of the community at heart.

Now I suggest we all go back to the classy part of the internet.

regards,
J


P.S.: @krnlde has contributed considerably to this project through support and advice.

**Comment by reggi** [comment]
Thanks for clarifying @janpaepke, and thanks for your response. I totally agree with you.

![280x280xclass-act-280x280 jpg pagespeed ic pm8k0xoklg](https://cloud.githubusercontent.com/assets/296798/6252372/da2b6dd2-b767-11e4-8ddb-8f9a3ec79a5b.jpg)

**Comment by oompt** [comment]
I don't understand this logic. Just because a package is on NPM, doesn't make it a "front end package." By not publishing on NPM, you make things way harder than they need to be for anyone trying to build a website without a thousand script tags everywhere and messy global name-spacing. So frustrating.
