### ISSUE TITLE
Animating multiple sections in opposite directions

### ISSUE THREAD

**Issue by gpartington** [janpaepke/ScrollMagic#214]
I'm trying to do something similar to what's described in [Issue #123]  (https://github.com/janpaepke/ScrollMagic/issues/123).

I have multiple sections that I'm trying to get to scroll in opposite directions. I'm having trouble getting the left sections to line up with the right section. Ideally I'd like the top of Left 1 to be at the top of the screen when Right 1 hits the top of the page

the fiddle is here: 
http://jsfiddle.net/aeecnd8w/1/

**Comment by janpaepke** [comment]
I think you made some sort of logic mistake, because if Left1 hits the top, when Right1 hits the top you will never see Left 2 or Left 3.
But since that is what you wrote, here's how you do it:
First to have the movement feel naturally in relation to the scroll movement, turn of easing, by supplying `ease: Linear.easeNone`.
Then change the duration to be exactly the window height (as this is the time it takes to scroll Right1 from the bottom to the top edge).
Finally change to target position of the left container to be where you want it to be at that point: `'-200%'`.

See here for the result: http://jsfiddle.net/aeecnd8w/2

Keep in mind, that the user may resize the window after loading and the duration will be off.
See here how to fix that: file:///Users/janpaepke/Desktop/ScrollMagic Project/ScrollMagic/examples/expert/responsive_duration.html

**Comment by gpartington** [comment]
hmm yes this is the effect I'm going for and I see what you're saying about the sections never advancing. If I wanted them to continue to scroll down in sequence with the right side would I just change the duration or set those up as different scenes?

**Comment by janpaepke** [comment]
well it really depends on the outcome you are going for. try to describe more accurately what you want to achieve.
I.e. "first  left1 comes in from top, right 1 from bottom and are fully visible at the same time, then left 2 comes in from top and right 2 from bottom.... " etc...

**Comment by gpartington** [comment]
OK thanks. I'm attempting to have separate right and left panels that slide in the opposite directions as you scroll down. so something like this:

1. First shows full screen title section then
2. as you scroll down Right 1 comes up from the bottom and Left 1 comes down from top
3. then as Right 2 comes up from the bottom the left side comes down so Left 2 then comes down from top
4. then as Right 3 comes up from the bottom the left side again comes down and Left 3 comes down from top. 

Ideally

**Comment by janpaepke** [comment]
Well with your current setup you just need to change the duration and movement distance of the left side's container: http://jsfiddle.net/aeecnd8w/4/
If you want to hide the left elements that already scrolled past at the end, you can wrap the whole thing in a container and make it `overflow:hidden`.
If you want to have the two staying together for a while you could pin the whole split content using 3 scenes at the appropriate offsets.

hope this helps.

**Comment by gpartington** [comment]
Thanks so much, this helps a lot. When you say wrap the whole thing in a container do you mean the entire page or just the split content?

**Comment by janpaepke** [comment]
Well the area were you want your divs to be limited to.
For example like so: http://jsfiddle.net/aeecnd8w/5/ or so: http://jsfiddle.net/aeecnd8w/6/
Setting the body to `overflow:hidden` is usually a sign of bad coding.

Does this resolve your issue?

**Comment by gpartington** [comment]
Thank you. It sure does

**Comment by lizzy-creative-covered** [comment]
Hi, It seems that these solutions are no longer working?

I want to create two columns that scroll in different directions, so as you scroll the left column goes up and the right column goes down.
