### ISSUE TITLE
I think, ScrollMagic needs MouseWheel normalization.

### ISSUE THREAD

**Issue by ealvizouri** [janpaepke/ScrollMagic#219]
ScrollMagic works great under Mac and scroll bar usage. But when it comes to use a mouse wheel It jumps pixels awful. Do you have any idea about how to implement and merge jquery-mousewheel on ScrollMagic? Thanks!

Or maybe with Greensock, I found this code for smooth scrolling. Uses ScrollToPlugin from GSAP Greensock.

```js
		var $window = $(window);		//Window object

		var scrollTime = 0.5;			//Scroll time
		var scrollDistance = 170;		//Distance. Use smaller value for shorter scroll and greater value for longer scroll
			
		$window.on("mousewheel DOMMouseScroll", function(event){
			event.preventDefault();
			var delta = event.originalEvent.wheelDelta/120 || -event.originalEvent.detail/3;
			scrollTop = $window.scrollTop();
			finalScroll = scrollTop - parseInt(delta*scrollDistance);
				
			TweenMax.to(
				$window,
				scrollTime,
				{
				scrollTo:
					{y:finalScroll, autoKill:true},
					ease:Power1.easeOut,	//For more easing functions see http://api.greensock.com/js/com/greensock/easing/package-detail.html
					autoKill:true,
					overwrite:5							
				}
			);			
		});
```

Thanks! xD!

**Comment by janpaepke** [comment]
Hi!
What you are describing is something called "mousewheel smooth scroll".
This isn't something ScrollMagic implements, because there are many different ways already out there to do that.
Some Browsers or Operating Systems behave differently (as you yourself mentioned) and implement it or don't.
There's even differences between trackpads.

My guess is your code is from [this tutorial](http://bassta.bg/2013/05/smooth-page-scrolling-with-tweenmax/)?
So if you want to make your page scroll smoothly I would recommend following that tutorial or use a plugin like [iScroll](http://iscrolljs.com/) or [jquery.smoothwheel](https://github.com/fatlinesofcode/jquery.smoothwheel).

Does this answer your question?

regards,
J

**Comment by ealvizouri** [comment]
Thanks! That's what I needed! :D
