### ISSUE TITLE
Scroll from the bottom up

### ISSUE THREAD

**Issue by irot** [janpaepke/ScrollMagic#225]
Hello.

Basically, the website I'm building navigates from the bottom up: Section A is at the bottom, then B above it, then C, etc.

My current code is based on the examples provided, and pretty much works when I scroll from top to bottom. But if I start at the bottom, while the previous section (Section A) animates out as it should, the next section (Section B) is already in its last frame.

I originally posted my question on StackOverflow before I thought of asking here: http://stackoverflow.com/questions/27987367/scrollmagic-from-the-bottom-of-the-page-up

What do I need to change to make it work from bottom to top? Please refer to the SO question for code samples, didn't want to repeat it here.

Thanks.

**Comment by justinmarsan** [comment]
Hoping you have rather simple animation, you can change the `Tween.to` to `Tween.from` (or the opposite).

This could get rather complex if you're using Timelines and stuff, things could get more difficult, you'd probably have to change your code.

**Comment by irot** [comment]
Sadly, it's far from simple: not just timelines, but multiple nested timelines.

After playing around with my code I managed to make it work how I want it but from the top down, now it's a matter of flipping either all my timelines, or the start/end triggers, if that's even possible.

**Comment by janpaepke** [comment]
Hi irot,

flipping the start-end triggers isn't the solution.
Let me explain why:
Let's take 3 scenes.
1 -> animates X from A to B
2 -> animates X from B to C
3 -> animates X from C to E

Now if you reverse the scenes and scroll bottom up, in theory what would happen is this:
3 -> animates X from C to E
2 -> animates X from B to C
1 -> animates X from A to B

That is because reverse would become forward if you'd invert the scene.

What I think you are looking for though, is this:
3 -> animates X from A to B
2 -> animates X from B to C
1 -> animates X from C to E

The problem though is that because you are scrolling bottom up what actually happens is this:
3 -> animates X from B to A
2 -> animates X from C to B
1 -> animates X from E to C

So the obvious solution is to define the tweens accordingly, similar to what @justinmarsan suggested.
If you define the tween for Scene 1 to go from E to C it will play from C to E when scrolling up, like you want.

Now from what I understand you already built complex tweens and are looking for an easy way to reverse them without rewriting them all.
Here's a quick solution for that:
- Invert the scene to tween relation (1st tween -> last scene, etc.)
- supply "{paused: true}" for all major timelines
- now remove the "setTween" method
- add the event listener below to each scene [untested]
```js
// scrollbound animations
scene.on('progress', function (e) {
    TweenForThisScene.totalProgress(1-e.progress);
});
// triggered animations
scene.on('enter leave', function (e) {
    if (e.type === "leave") {
        TweenForThisScene.play();
    } else {
        TweenForThisScene.reverse();
    }
});
```
Also I suggest you have a look at this:
https://github.com/janpaepke/ScrollMagic/issues/141

**Comment by janpaepke** [comment]
Update: There's another thing you might want to try, not sure if it works.
Set the Timeline to {reverse: true} and then add it into another timeline.
Maybe this way  you can keep using the "setTween" methods...

**Comment by irot** [comment]
Thanks for that Jan, you were right: it was as simple as setting my major timelines to `.reverse(true)`. So the bottom up issue is resolved, now I need to make it such that each scene plays in _and_ out, and your triggered animations example above looks like it might do the trick.

Thanks again.

**Comment by janpaepke** [comment]
glad I could help.
