### ISSUE TITLE
Problem with script

### ISSUE THREAD

**Issue by dardos** [janpaepke/ScrollMagic#227]
Hi,
I need some help!
I developed a website using TweenMax and work's fine on test page but when I put on the oficial page nothing happens. The ScrollSceneIndicators doesn't appear and the animations occur the same.
Don't know if some conflict with another script that I used is happen.
Really appreciate with you can help me with this bug.
Link with the problem:
www.dardosdesign.com.br/new
Link with no problem:
www.dardosdesign.com.br/new/teste.html

Regards

**Comment by johnfmorton** [comment]
It looks like you might be calling the "document ready" function using jQuery before you've loaded jQuery. 

I see "Uncaught ReferenceError: $ is not defined" as the first message in an error log when I look at the page.

**Comment by dardos** [comment]
Hi John!

Thanks for the attention and so quickly!
I removed "document ready" but still doesn't work.

I really don't understand why works fine on teste.html.

**Comment by johnfmorton** [comment]
I think rather than removing it, you should be sure to include your Javascript that is in the head of the page somewhere below the JS includes in your footer. For example, put that JS in the header right above your Google Analytics code block on line 809.

**Comment by dardos** [comment]
I tested with the "document ready" and without but still not work!

The JS now is above GoogleMaps code.

**Comment by janpaepke** [comment]
Hi Dardos,
As John already pointed out, your problem is that you try to use jQuery before it is loaded.
You are loading jQuery in line 768, way after the block where you try to use it (358).
The obvious solution is to make sure that jQuery is loaded before referencing it, i.e. putting it higher up in the markup.
Since

**Comment by dardos** [comment]
Hi Janpaepke,

I read and did everything on the site, but I didn't found nothing to solve the problem.

I'm sorry to bring to you my problem! Just thought that your experience with this plugin would help me. I just don't understand why you need to be so rude. 

Thanks again for your attention!

**Comment by janpaepke** [comment]
Hi Dardos,
huh? It wasn't my intention at all to be rude!
It's just that this is a support forum for ScrollMagic and I need to be aware of what is useful for other ScrollMagic users.
This issue has nothing to do with ScrollMagic and if you are looking for general javascript advice I suggest [Stackoverflow](http://stackoverflow.com).

If you really read everything I'm curious as to why you didn't close in on the problem yourself, since checking the console is number one on the list...
I'm also curious why you didn't post a permanent link, as also requested in the guidelines.

Were you able to resolve this now?

**Comment by dardos** [comment]
Hi Jan,

It was my fault! Because I just didn't think about the position of the
jQuery and the script.

Do you know?! I was so confused why in teste.html it's working and
index.php not, that I didn't think in another solution.

I used the console and didn't check the basics things. A lot of pages open,
test pages, versions and another things that I didn't realized.

I'm sorry again to bring to you my problem!

Now it's working and thanks to your team for the support that you don't
needed to do!

Regards


*Eduardo Carvalho*
carvalho.edu@gmail.com

**Comment by janpaepke** [comment]
Glad you could work it out...
