### ISSUE TITLE
Trigger "onCenter" but positioned on bottom?

### ISSUE THREAD

**Issue by dipovespo** [janpaepke/ScrollMagic#228]
Hi, I want to ask why the trigger is positioned on bottom, eventhough it's "onCenter" ?
Here's the live example: http://houseofinfographics.com/scroll/baru.html

But when I tried to replicate the issue on jsfiddle it's on the center, can you tell me what's wrong?
http://jsfiddle.net/ananggadipa/240uwyLj/1/

And why is on the beginning there is some glitch, like the start and finish was on top of the page (it will reset to normal position when the scrolling started) screenshot attached.

![screenshot 2015-01-27 09 32 24](https://cloud.githubusercontent.com/assets/5245236/5912508/c989cf4e-a607-11e4-8118-688fd80b81f3.png)

Btw, thank you for the great work :)

**Comment by janpaepke** [comment]
Hi @dipovespo,

Please make sure you understand what term describes what.
There are three properties influencing the start of a scene.

The `triggerHook` is the point relative to the viewport, that defines, what position the scene needs to pass in order to trigger. It is represented by the blue marker.

The `triggerElement` defines an element in DOM flow, whose position needs to run past the `triggerHook` in order to trigger the scene.

The `offset` is a numeric value that is added to the `triggerElement` position, if defined, or the start, if not defined.

Mind that all three values are optional.

Now as you can see in your example the blue marker is vertically centered in the viewport. So it's exactly what's expected, if you set it to "onCenter".

The "glitch" you describe is due to unnecessary or wrong offset values and triggerElements.*
Here's a resolved version: http://jsfiddle.net/240uwyLj/3/
What I did was change the offset of your last scene from -900 to 100 and also use the element `"#trigger"` as the trigger element, same as the other scenes.

There is a lot of redundant and unnecessary code in your example.
Please make sure you fully understand the code, instead of wildly copying it from various sources.

Hope this helps.

regards,
Jan

----
*Here are the details as to why the positioning of the indicator is off until scrolling starts:
For the scene that does the pin you used a trigger element that below the element you are pinning.
Since you also (implicitly) have set `pushFollowers` to true the element is pushed down, after the scene is fully initialized. So suddenly the start point is further down than when it was when the indicators are initialized. That is why the initial indicator position is off. This is auto-corrected as soon as you start scrolling, as the scenes are updated then.
Note that this inconsistency is fixed in ScrollMagic 2.0 (currently in alpha phase)

**Comment by dipovespo** [comment]
Hi @janpaepke,

First many thanks for your detailed reply, I really appreciate it.
For triggerHook yes I understand that, the one I mean is the triggerHook, sorry not specify it. But the problem appear here: http://houseofinfographics.com/scroll/baru.html (and on my local files), not in the js fiddle, eventhough it share the same code. Here is the screenshot:

![screenshot-2015-01-29-08 32 07](https://cloud.githubusercontent.com/assets/5245236/5951100/c8963bca-a794-11e4-9079-34836091b82c.png)

And in one division could it be more than one trigger hook? Because when I try to change triggerHook individually (with different number), not from global option it both shows up differently.

Thank you for the cleaned version, yes I'm try to learning it by first copying the example code and try to modify it to get what I'm looking for. 

Thanks for your help, Jan.

Regards,
Dipa

**Comment by janpaepke** [comment]
Hi Dipa,
I gotta admit this one had me stunned for a bit.
The reason the trigger position is off, is that `$(window).height()` returns different values in the fiddle and in your site.
In the fiddle it correctly returns the viewport height, while on your site it is the document height.
And because that height a lot larger and is used for the calculation of the triggerHook position (0.5*height) the hook is way further below, than it should be.

So why is jQuery returning a wrong height?
I gotta admit it took me a while but as usual [stackoverflow](http://stackoverflow.com/questions/12103208/jquery-window-height-is-returning-the-document-height) had the answer:
The reason is that your site is missing a __doctype__.
If you add `<!DOCTYPE html>` at the top it should work as expected.

As per your second question:
Yes, you can set a different triggerHook for each scene.

Hope this clears things up,
J

**Comment by dipovespo** [comment]
Ahhhh so that's the problem, many2 thanks Jan!
I really appreciate your answer! 

Regards,
Dipa

**Comment by janpaepke** [comment]
glad I could help.
