### ISSUE TITLE
flickering opacity when scrollup

### ISSUE THREAD

**Issue by fabianjaehnke** [janpaepke/ScrollMagic#235]
Hi,
i tried to pin a section which contains an image which gets fadeIn while scrolling. This works fine, but when i scrollUp, the image changes its opacity a couple of times very fast.
testet in lastet chrome
 
thanks for any advise or help
 
Demo: http://codepen.io/fabianjaehnke/pen/myMdEe

**Comment by janpaepke** [comment]
Hi Fabian,
For some reason you added two controllers for the same viewport and scroll direction, which was causing the problem.
Here's a corrected version: http://codepen.io/janpaepke/pen/KwvEGo

regards,
J

**Comment by fabianjaehnke** [comment]
Hey,
thanks for the quick response and the solution for the 2 controllers,

But the issue still appears when scolling from bottom to top.
in your fork i scroll from the third (blue) section up all the way, then the img gets an opacity of 0 for some milliseconds an changes back to 1

regards
fabian

**Comment by janpaepke** [comment]
Now that one's a little tricky :) (at least to wrap your head around).
short version: The reason is that the triggerElement for the opacity tween is inside of the element that you pin.

solution:
Use the same trigger element for both scenes: http://codepen.io/janpaepke/pen/BydXpY

long version:
When an element is fixed this means that you can never scroll past it (duh). Pinning in ScrollMagic is achieved by setting elements to fixed for set periods of time. This is why when you use an element both as pin target and as trigger element ScrollMagic internally realizes that and uses the position of the pin spacer position instead of the element position. Because otherwise it would never move in relation to scroll position.
Now this get's more complicated between different scenes and for performance reasons can't be done for children of pinned elements.
When scrolling down ScrollMagic will update the scenes from top down, when scrolling up it will update them bottom up.
So what's causing the flickering is this:
When scrolling down the pin will always trigger before the opacity tween, so no problem occurs regarding the positioning. When scrolling up the opacity triggers, thinks it needs to update and does that. Then the pin triggers, changing the position of the trigger element for the second scene. Suddenly the second scene is past it's trigger again and goes back to finished.
This is what causes the flickering.

**Comment by fabianjaehnke** [comment]
thanks for your time and the long version, helped me a lot

**Comment by wfendler** [comment]
Another possible solution for the lazy if anyone finds there way to this problem like me:

Put a transition/transition-delay on the element that is flickering. I was already transitioning that element so I added a transition delay when the class is being removed. Won't work for every case but worked for me!

```scss
.thing {
  opacity: 0;
  transition: opacity .5s ease;

  // This delay stops flickering when scrolling up when
  // the class is getting removed/added quickly
  transition-delay: .5s;
  
  &.is-visible {
    opacity: 1;
    // When the class is added there's no delay
    transition-delay: 0s;
  }
}
```
