### ISSUE TITLE
Multiple Full Page Pins

### ISSUE THREAD

**Issue by owengalenjones** [janpaepke/ScrollMagic#236]
Hi, I'm trying to implement 5 separate sections that are all pinned for the duration of the document.  Each one will then scroll above the previous pinned section.  This works well except for the final section which causes some major jittering / bouncing when start hits the trigger.

http://codepen.io/anon/pen/azLbLP?editors=100 or http://jsfiddle.net/mnqy6hr1/embedded/result/

For example here is the literal last scroll to make scene5's trigger hit start:

```
(ScrollMagic) -> updating Scene 1/5 (5 total)
(ScrollMagic) -> updating Scene 2/5 (5 total)
(ScrollMagic) -> updating Scene 3/5 (5 total)
(ScrollMagic) -> updating Scene 4/5 (5 total)
(ScrollMagic) -> updating Scene 5/5 (5 total)
(ScrollScene) -> event fired: update -> Object {startPos: 3090, endPos: 3090, scrollPos: 3092}
(ScrollScene) -> event fired: enter -> Object {progress: 1, state: "DURING", scrollDirection: "FORWARD"}
(ScrollScene) -> event fired: start -> Object {progress: 1, state: "DURING", scrollDirection: "FORWARD"}
(ScrollScene) -> event fired: progress -> Object {progress: 1, state: "DURING", scrollDirection: "FORWARD"}
(ScrollMagic) -> updating Scene 1/5 (5 total)
(ScrollScene) -> event fired: update -> Object {startPos: 3090, endPos: 3090, scrollPos: 2932}
(ScrollScene) -> event fired: progress -> Object {progress: 0, state: "BEFORE", scrollDirection: "REVERSE"}
(ScrollScene) -> event fired: start -> Object {progress: 0, state: "BEFORE", scrollDirection: "REVERSE"}
(ScrollScene) -> event fired: leave -> Object {progress: 0, state: "BEFORE", scrollDirection: "REVERSE"}
(ScrollMagic) -> updating Scene 2/5 (5 total)
(ScrollMagic) -> updating Scene 3/5 (5 total)
(ScrollMagic) -> updating Scene 4/5 (5 total)
(ScrollMagic) -> updating Scene 5/5 (5 total)
```

All that just from one scroll of the mousewheel.  You can see in there it appears that is is jumping from `scrollPos: 3092` to `scrollPos: 2932`

**Comment by janpaepke** [comment]
Hi Owen,

this is indeed a bug. Although one that was fixed a long time ago.
In your pen you use ScrollMagic 1.0.1 whereas the current version is 1.3.0.

If you upgrade the version it works as expected: http://codepen.io/janpaepke/pen/yyzJgz

please always use the latest version.

Details:
The reason for this bug was a problem when calculating the pin spacers, which replace the pinned elements in document flow, while they are pinned.
It concerned the margins.
So basically when you god all the way to the bottom the last element was pinned, and taken out of DOM flow. Because the spacers were not high enough this caused the content's total height to get smaller.
This in turn caused the page to be shorter, so the total height you could scroll got shorter.
That in turn caused the scrollbar to jump up past the trigger point of the last scene, causing the element to be pinned again and the DOM getting longer again. Voila: Jitter.
That is also why the error would not appear on smaller viewport sizes (try a window height of like 500 px). The jump back simply wasn't big enough here to jump past the trigger.

**Comment by owengalenjones** [comment]
@janpaepke ah thank you, that sounds promising.  Just an FYI I would absolutely normally download the latest version, I got 1.0.1 from Bower so it's possible they are distributing an out of date version.

**Comment by janpaepke** [comment]
Thx 4 the info, I will check up on that...
