### ISSUE TITLE
Uncaught referenceerror

### ISSUE THREAD

**Issue by CalebEverett** [janpaepke/ScrollMagic#237]
Hi Jan, sorry if this is really basic. I did see another issue where an older version of jquery was being used and that wasn't a solution here. I'm using version 2.1.3. The problem I'm having is that when I include version 1.3 of ScrollMagic, I'm getting an uncaught referenceerror: ScorllMagic not defined. When I use version 1.0.8 the error doesn't occur.  Here is how I'm setting up ScrollMagic

```javascript
var controller = new ScrollMagic({
    globalSceneOptions: {
      triggerHook: "onLeave"
    }
  });
```

Again, sorry if this is super basic, but is there anything I need to do differently with version 1.3. I checked the version history and saw something about one object with the AMD loading, but wasn't sure if that was the problem.

Thank you, Caleb

**Comment by krnlde** [comment]
Can you provide a jsfiddle with your problem?

**Comment by janpaepke** [comment]
If you copied the error message, then the problem is that you misspelled "ScrollMagic".

If you didn't, my guess is that either ScrollMagic isn't loaded or referenced with a different handle (for example if you use AMD).
If you do use AMD, please check here to find out more on how to use it: https://github.com/janpaepke/ScrollMagic/wiki/Getting-Started-:-Using-AMD

If you still can't figure it out...
... please clarify you environment (synchronous loading or AMD).
... please provide the full code (wrapper, etc) or better yet provide a fiddle, like @krnlde suggested.

**Comment by janpaepke** [comment]
@CalebEverett Any updates on this?

**Comment by CalebEverett** [comment]
Hi, thanks for following up. I had an error in the set up. My apologies,
you can close. Thank you.

On Wednesday, February 18, 2015, Jan Paepke <notifications@github.com>
wrote:

> @CalebEverett <https://github.com/CalebEverett> Any updates on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janpaepke/ScrollMagic/issues/237#issuecomment-74829660>
> .
>


-- 
Caleb Everett
Career College of California
201 E. 4th Street, Suite 200
Santa Ana, CA 92701
(714) 243-8614 phone and fax
www.careercalifornia.edu

Facebook <http://www.facebook.com/CareerCalifornia> | Twitter
<http://twitter.com/careercalif> |  LinkedIn
<http://www.linkedin.com/company/941062> | G+
<https://plus.google.com/b/104968762557101611990/104968762557101611990/posts>

**Comment by janpaepke** [comment]
No worries, glad it worked out. :)
