### ISSUE TITLE
Is there a standardized measure for offsets and duration or just pixels?

### ISSUE THREAD

**Issue by wmodes** [janpaepke/ScrollMagic#240]
In determining triggers and duration, are there relative units available that don't depend on the size of the viewport? 

You are welcome to look at my first rough test:  http://doc.peoplesriverhistory.us/

I appears that offsets and durations are defined in pixels relative to the position of the triggerElement. Thus, a negative offset says start before the triggerhook hits this element, while a positive offset says start after this element (depending on the trigger position, I guess, but I didn't get this to perform as I expected).

I have been forced to define a "winUnit" equal to the height of the viewport if scrolling vertically or the width if scrolling horizontally.

```js
    var winWidth;
    var winHeight;
    var winUnit;
    fullDelay = 2;

    // Initial set and callback
    setScreenSizes();
    $(window).resize(function() {
        setScreenSizes();
    });

    // Determining size of screen for fullscreen functions
    function setScreenSizes () {
        winWidth = $(window).width();
        winHeight = $(window).height();
        winUnit = winWidth;  // for horz scrolling

        $(".content").width(winWidth);
        $(".content").height(winHeight);

        for (i = 1; i <= sectionTotal; i++) { 
            $("#section"+String(i)).width(winWidth * fullDelay);
            $("#section"+String(i)).height(winHeight);
        }
    }
```

Defining in terms of pixels is extra challenging when the size of the window could change. Thus I have a window resize callback. However, do I then need to redefine all of my triggers as well. Awkward.

So my triggers are set in terms of winUnits:

```js
    // Pin section
    var scene = new ScrollScene({
        offset: winUnit/2,
        triggerElement: "#content2",
        duration: winUnit*(fullDelay-1),
        //pushFollowers: false,
    })
      .setPin('#content2')
      .addTo(controller)
      .addIndicators({suffix: '2a'});
```

Or in a more complicated example:

```js
    // Trigger background video start and end
    var scene = new ScrollScene({
        offset: -winUnit/2,
        triggerElement: "#content2",
        duration: winUnit*(fullDelay*2),
        //pushFollowers: false,
    })
        .on("start end", function (e) {
            BV.getPlayer().play()
        })
        .on("enter leave", function (e) {
            BV.getPlayer().pause()
        })
        .addTo(controller)
        .addIndicators({suffix: '2b'});
```

Is there a relative unit I don't yet know about? Or how have others dealt with this in the past? Suggestions welcome.

**Comment by janpaepke** [comment]
>I appears that offsets and durations are defined in pixels relative to the position of the triggerElement. Thus, a negative offset says start before the triggerhook hits this element, while a positive offset says start after this element.

correct.

You are also correct in assuming, that durations often depend on the viewport size.
Offsets however do not - or at least only very rarely.

Let me explain one by one:

### duration

Currently ScrollMagic does not support relative units. It does however support a callback function as value for duration. ([see docs](http://janpaepke.github.io/ScrollMagic/docs/ScrollScene.html#ScrollScene))
This enables you define a function, returning your winUnit for the duration.
Now you'll still have to update this variable on resize, but at least you don't have to update each scene manually.
Yes you could have the callback directly return  the viewport size but you shouldn't - for performance reasons.
Check out this example to learn more: http://janpaepke.github.io/ScrollMagic/examples/expert/responsive_duration.html

You think this still feels a like a little bit of a pain?
You're right again! :)
For that reason ScrollMagic 2.0, currently in beta, [will support relative units](https://github.com/janpaepke/ScrollMagic/blob/development/CHANGELOG.md#features).
You'll be able to simply set a duration to "100%" to keep it exactly at viewport size.

### offset

The offset is meant to be used to influence the trigger position relative to a trigger element, or just to set it numerically, if no trigger element is supplied.

What I think you need to understand is how triggerElement, offset and triggerHook play together to determine the start position of the scene.
Instead of setting the offset to `-winUnit/2` you can set the `triggerHook` to 0 or `"onLeave"` for the same effect. The same goes for an offset of `winUnit/2` - this would correspond to a `triggerHook` of `1` or `onLeave`.

I think this becomes the most obvious (and easiest to understand) if you play around with the values here: http://janpaepke.github.io/ScrollMagic/examples/basic/scene_manipulation.html

hope this helps.
regards,
J

**Comment by wmodes** [comment]
Jan, thanks for your response. Does the offset also support a callback so I can use it similarly to recalculate winUnit?

**Comment by janpaepke** [comment]
No because I haven't found a scenario where this is really necessary.
Adding this feature would mean worse performance and since I don't see the benefit, it hasn't been added...

**Comment by wmodes** [comment]
A typical use for me is that I want to trigger an event at a scroll position one or two winUnits before an element makes its appearance. Especially since I am using scroll magic to trigger background audio and video.

**Comment by janpaepke** [comment]
I see.
Well this is an edge case none the less.
There's two ways you could approach this:
 1. use a relative positioned triggerElement that has an offset of `-200vh`
 2. or (if u [can't or don't want to use use vh](http://caniuse.com/#search=vh)) update the respective offset(s) on resize.

Remember that you can change all Scene options on the fly, so you could add all the scenes that need their offset to be updated to an array and then walk it on resize.
Smth like that:
```js
var offsetScenes = [];
$(window).on("resize", function(e) {
  var height = $(window).height();
  $.each(offsetScenes, function(index, scene) {
    scene.offset(height*2);
  });
});
/* ... add scenes to array ... */
```

**Comment by wmodes** [comment]
That's a good idea. Thanks.

**Comment by janpaepke** [comment]
Glad I could help. :)
