### ISSUE TITLE
Expanding elements during scrolling result in incorrect scrollTo position.

### ISSUE THREAD

**Issue by bummzack** [janpaepke/ScrollMagic#241]
First of all, let me thank you for the awesome ScrollMagic plugin. I'm really glad it exists ;-)

I encountered a problem with `scrollTo` and shrinking/expanding elements. If an element grows in height during scroll, the scrollTo positions are off. Here's a fiddle that illustrates the problem:
http://jsfiddle.net/4a53ajm1/1/

Just click on "Section 3" in the top left navigation to observe the behavior. The correct scroll position would be so that the "Section 3" perfectly aligns with the top of the viewport.

I understand that this is somewhat an edge-case and maybe not supported by your plugin. Maybe there's a really elegant workaround I'm missing here?

**Comment by janpaepke** [comment]
Hi there!
Glad you like ScrollMagic.

This is not actually an edge case. There was a similar issue here before, but I can't find it right now.

What's happening is actually totally expected behavior and technically the `scrollTo` positions aren't off, they are spot on.
What I mean by that is that at the time you are clicking the button the scroll offset for section 3 is exactly where it scrolls to. The position of section 3 changes implicitly, because the above element changes in size. How should our script know that before it even happens?
So as I said _technically_ what's happening is totally correct.

But obviously to us it looks wrong, because we want it to scroll to section 3.
So how can we achieve that?
The solution might be obvious: We make sure the position of section 3 doesn't change.

This can be achieved for example by making section 2 positioned absolutely.
If it is its size will not affect the DOM flow anymore.
This also means that we need to push down our section 3 to not overlap our section 2.
We can do that with margins and end up at this working version:
http://jsfiddle.net/janpaepke/4a53ajm1/2/

This kinda sucks, you say, because we can't have dynamic heights and the section 3 doesn't move when section 2 is expanding?
Well if you want that, you'll have no choice but to calculate the position where section 3 ends up before it does.
The easiest way to do that is to skip the animation to the end, get the position and then set it back to where it was and play it as normally.
So that will look like this: http://jsfiddle.net/janpaepke/4a53ajm1/3/

Granted that makes it more complicated but if  you change the position of elements in js (which is what you do if you animate with it) you'll have to either make sure the changes are irrelevant (solution 1) or calculate them in (solution 2).

Finally I would advise you to definitely have a look at the [Anchor Link Scrolling Example](http://janpaepke.github.io/ScrollMagic/examples/advanced/anchor_link_scrolling.html).

hope this helps.
J

**Comment by bummzack** [comment]
Thanks for the lengthy explanation. It's all perfectly clear. I feared I'd have to implement something akin to your second workaround. I didn't think about forwarding the tween and reading the final state though! That's pretty neat.

I'll close this, since you answered pretty much everything I need to know. Thanks again.
