### ISSUE TITLE
Parallax-ish background with Anchor Link Scrolling

### ISSUE THREAD

**Issue by ryanbuiltthat** [janpaepke/ScrollMagic#242]
I'm using the code snippet from the "Anchor Link Scrolling" example and it's working great. I'm trying to combine concept from the parallax section example but it's really jerky and the effect on the background isn't activated although when I run the inspector I can see the top: value changing. Any insights on how to combine the two examples? Anchor based scrolling with parallax support?

I guess a better question would be...do I need to init a new controller? Currently I'm adding the parallax scene to the click event. Trying to keep it somewhat dynamic so I don't have to create a new scene manually for each new section....if that's possible.

```js
// init controller
var controller = new ScrollMagic();

// build tween
var tween = TweenMax.from("#child", 1, {autoAlpha: 0, scale: 0.7});
var ptween = TweenMax.from("#parallax_parent > div", 1, {top: "-80%", ease: Linear.easeNone});
// build scene
var scene = new ScrollScene({triggerElement: "div#parent", duration: 200, triggerHook: "onLeave"})
                .setTween(tween)
                .addTo(controller);

// change behaviour of controller to animate scroll instead of jump
controller.scrollTo(function (newpos) {
    // add offset
    newpos -= 80;
    TweenMax.to(window, 1, {scrollTo: {y: newpos}});
});

//  bind scroll to anchor links
$(document).on("click", "a[href^=#]", function (e) {
    var id = $(this).attr("href");
    var parent = $(this).parent().parent().attr('id');
    if ($(id).length > 0) {
        e.preventDefault();

        // add parallax effect
        new ScrollScene({triggerHook: "onEnter", duration: $(window).height()*1,triggerElement: parent})
                        .setTween(TweenMax.from(id+"_fig", 1, {top: "-80%", ease: Linear.easeNone}))
                        .addTo(controller)
                        .addIndicators({zindex: 1, suffix: "1"});

        // trigger scroll
        controller.scrollTo(id);

        // if supported by the browser we can even update the URL.
        if (window.history && window.history.pushState) {
            //history.pushState("", document.title, id);
        }
    }
});
```

**Comment by janpaepke** [comment]
Hi Ryan,

two things:

1. Use animate `y` instead of `top`. This will create a transform animation instead of animating the top position of the element. Long story short: performance wise this is a lot better.
The examples are already updated and will be published with ScrollMagic 2.0 - [see here](https://github.com/janpaepke/ScrollMagic/blob/5e69d3b6745d328cadee726900a7d19e66e783a3/examples/advanced/parallax_sections.html#L78)

2. With your current code you are actually creating a new scene every time you are clicking on a link for the particluar target of your scroll.
Once you clicked on each of them once the page should behave as desired.
But my guess is this isn't what you were looking for...

Instead of creating a scene every time the user clicks you probably want to create one for each parallax section.
To do that use a `$().each()`.
For an example see here: http://stackoverflow.com/questions/28393992/reuse-tweens-in-different-scrollmagic-scenes

**Comment by ryanbuiltthat** [comment]
Thanks for the quick response. I'll give it  go now and report back. Curious though, in the parallax example, you set global scene options. Should I move those options to the scene created by the loop or should I keep them as global options and just modify the anchor link scene options to counter-act the global settings? if that makes any sense at all....

**Comment by janpaepke** [comment]
that's totally up to you!
The `globalSceneOptions` is just a convenient way if you want to apply the same settings to all scenes.
You don't HAVE to use it, it's your choice...

**Comment by ryanbuiltthat** [comment]
Note: the parallax documentation you linked to above differs in the class syntax than what's on the website. Is this a version issue?

That's awesome!! Ok this may be outside of the scope of this thread and page, if so i can take it to SO. But I can't get this loop to target the right Id to save my life. Do I have this right in theory at least? I'm the background is contained in a figure tag. The previous sibling is a div element that I would like to be the trigger...

<div class="slide">
    <div id="container1" class="slide-cols container-fluid">
      <div class="row">
      	<div class="col-xs-2 col-md-2 slide-image">
        	<figure><a href="#"><img src="example.com/sample.png" alt="..." /></a></figure>
      	</div>
      	<section class="col-xs-10 col-md-8 col-md-offset-1 slide-text">
        	<header class="cols-row-header cf section-header no-group">
          		<h3 class="section-header-main  header-class">...</h3>
        	</header>
        	<p>...</p>
        	<p><a href="#hpg" class="page-scroll">. . .</a></p>
      	</section>
    </div>
    <div class="page-arrow"><a href="#nextContainer"><i></i></a></div>
  </div>
</div>
<figure id="hero" class="slide-hero" data-section-type="plx"></figure>

And My Javascript....

var controller = new ScrollMagic();
var targets = [];
// push the figures to triggers
$("figure[data-section-type='plx']").each(function(i) { 
	targets.push($(this).attr('id'));
});
		triggers.forEach(function(trigger, index){
			//make tween
			var t = $(trigger).siblings('div').attr('id');
			var thisTween = TweenMax.from(trigger, 1, {y: "-80%", ease: Linear.easeNone}); 
			// scene
			new ScrollScene({
					triggerElement: '#' + t,
					triggerHook: "onEnter",
					duration: "200%"
				})
				.setTween(thisTween)

				.addTo(controller);
			});

But this only seems to effect the first figure and that's it. Is this an issue with my lack of jQuery skills or am I mis-using the ScrollScene class?

**Comment by janpaepke** [comment]
> Note: the parallax documentation you linked to above differs in the class syntax than what's on the website. Is this a version issue?

Yes. As I said it **will** be published with ScrollMagic 2.0 - that isn't released yet.

For the same reason you **can not** use `duration: "200%"` as that is a feature that is only available in 2.0

Regarding your code, you're making it a lot more complicated than it needs to be. There's several reasons why it may not work the way you want it to, one of them being that you use an ID multiple times.
Note that you don't have to supply IDs neither to TweenMax nor ScrollMagic - if you have the elements already, just supply those!

check this out:

```js
var controller = new ScrollMagic();
// create scenes
$("figure[data-section-type='plx']").each(function() { 
	//make tween
	var thisTween = TweenMax.from(this, 1, {y: "-80%", ease: Linear.easeNone}); 
	// scene
	new ScrollScene({
		triggerElement: $(this).prev(),
		triggerHook: "onEnter",
		duration: $(window).height() * 2
	})
	.setTween(thisTween)
	.addTo(controller);
});
```

**Comment by ryanbuiltthat** [comment]
My dad has told me since I was a kid to stick to the KISS principle and I never start out that way! Thanks for reminding me to Keep It Simple Stupid! I'll give it a go when I get some coffee down my gullet. Thanks!

**Comment by ryanbuiltthat** [comment]
You can close this. I think I have to just refractor my HTML to make this work. For whatever reason I can't get the parallax section example to work. When I initialize it it seems to trigger onload so the target element moves up -80%. I even tried combining it with the one-page parallax example from I Hate Tomatoes (after removing Skrollr) but still can't get it to work. Is there specific CSS I need to have ahead of time? Greensock docs mention that the `Tween.from()` takes the starting value as the destination and you specify the offset so to speak if I understand that correctly. Either way when I load the page my element is moved -80% up.

**Comment by ryanbuiltthat** [comment]
So I went so far as to completly ditch that page and start over. I'm trying to use this as a hands-on way of learning Scroll Magic and I'm failing. I used the basic setup from Petr Ticy's One-page parallax example, removed skrollr and tried to wire up SM. The first problem I seem to be having is if I want the first slide to have an effect when the user begins to scroll, it seems like the Tween.from() even is being triggered on load. So the targetElement is -80% higher than it should be. 

Then I thought it was my trigger that was off. So I set my trigger to the second slide, that still didn't work. I'm at a loss here. Here's a codepen to give you an example of what I'm talking about. The first slide is just a narrow stirp, it's being translated up -80% on load.

http://codepen.io/ryanbuiltthat/pen/xbYJzX

**Comment by janpaepke** [comment]
Hi Ryan,
again the documentation helps you.
A `.from()` tween by definition creates a tween FROM certain values to the current ones. So it will make them go from -80% to 0 (assuming that's the value at the point of tween definition).
See here: http://greensock.com/docs/#/HTML5/GSAP/TweenMax/from/

The trigger position is something you define in ScrollMagic, NOT in TweenMax.
If you want to have a tween that starts right, when the user scrolls, just don't supply a triggerElement or offset at all.

Here's your corrected pin: http://codepen.io/janpaepke/pen/VYQVqG

It still won't work as expected, because the div containing your content is inside the div containing your background. So if the background moves, so does the text, which prevents you from seing a parallax effect.

It seems to me you should focus on understanding the core principles before trying something like this.
Please have a look at the GSAP getting started guide: https://greensock.com/get-started-js
And also the ScrollMagic HowTo: https://github.com/janpaepke/ScrollMagic/wiki/Getting-Started-:-How-to-use-ScrollMagic

Next please follow the support guidelines: https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md

best regards,
J

**Comment by ryanbuiltthat** [comment]
Thanks so much for your time. I appreciate the guidance and patience.

**Comment by janpaepke** [comment]
Glad I could help.
If you want to support the project consider making use of the donation button or have a closer look at the banner at the bottom of the demo page.
regards,
J
