### ISSUE TITLE
Issues with scrolling within a container

### ISSUE THREAD

**Issue by lahmiro** [janpaepke/ScrollMagic#244]
I am new to ScrollMagic. I created a website on which people can scroll pictures within a container.
Here is the link: http://lahmiro.github.io/camera/index.html I used ScrollMagic and GSAP to create a curtain effect, but it didn't work properly on big screens (e.g. iMac, ps, it worked fine on my MacBook). The pictures are kinda off the edges while scrolling down ([screenshot](https://40.media.tumblr.com/cbf9f2e7a07d9a97b758988f5505c348/tumblr_nk06tv9tEh1rlvfuoo1_400.png)).

In my js file, I used a for loop to calculate the offset for each picture and set tweens and pins. I think there might be some problems of pinning elements in this way, but I don't know how to solve it... I'd appreciate if anyone could give me some suggestions. Thank you ;)

**Comment by janpaepke** [comment]
Hi!
First of all it is important to know which browser you are referring to.

My guess though is, that your phenomenon is caused by "rubber band scrolling", which means that the browser moves the viewport past its actual bounds.
This can cause positioning problems for fixed elements.

Please try to add this css to your site and let me know if the error still occurs:
```css
html, body {
  height: 100%;
  overflow: hidden;
}
```

**Comment by lahmiro** [comment]
Thank you for your reply. I tried to add the code you suggested. I tested it on Chrome, Opera, Firefox and Safari on an iMac, but it still didn't work...

**Comment by janpaepke** [comment]
Well if you don't want us to keep guessing I'm gonna need you to give more information, because I can not reproduce this.
Maybe you can post a screencast?

**Comment by lahmiro** [comment]
Here is the link for the screencast: https://www.youtube.com/watch?v=wnKLsa9M7vk&feature=youtu.be
Thank you for your patience!

**Comment by janpaepke** [comment]
Hi @lahmiro !

Sorry for the delayed answer, I was on holidays...

It seems like the demo link isn't working anymore (something that's explicitly asked in the support guidelines).
Please provide a (permanent) link to your demo.

Or did you manage to solve this issue?

**Comment by lahmiro** [comment]
Thank you for keeping tracking of this post!:) The new link is http://lahmiro.github.io/camera/index.html. Sorry that I changed it before for a better file management.

**Comment by janpaepke** [comment]
I was confused when again it looks perfect for me (couldn't reproduce).
Then I reread your initial post you said it looks okay on macbook and not okay on big screen.
Is it possible that your macbook is retina and the big screen is not?
Do you have any CSS directives that change behavior based on resolution?
When I get back home I can test this with my external monitor...

**Comment by lahmiro** [comment]
I tested it on different iMacs. I looked over my CSS code, I didn't find something suspicious in the code. I gave the outer container "#imgBox" a fixed width and height, and set the width and the height of the inner container "#imgContainer" well as the height of the divs as "100%". Otherwise there are some code for positioning the "#imgBox". I was confused as well, but at least it worked on macbook.

**Comment by janpaepke** [comment]
HA! I got it!
Now THAT was a tricky one! :)

I was really confused that as soon as I got to my office I had the same issue appear not only on my external screen, but also on my macbook.
At first I was suspecting you to have changed something.
But then it dawned on me: The difference isn't the screen. It's the mouse!

When using a trackpad the scrollbar does't influence the content width.
But when you use an external mouse (as you do on iMacs and as I do in my office) the browser automatically adds a fixed width scrollbar inside the scrollable content.
That is what's causing the weird space on the side of the images.
The reason you don't see the scrollbar is because it's covered by the pinned image, that uses the full width of the scroll container instead of it's parent (INSIDE of the scroll container).
So the image basically covers the scrollbar.

To fix this add this to your CSS:
```css
#imgContainer img {
  width: 100%;
}
```

Now the next problem for you will be that because of maintaining aspect ratio the image doesnt fill the whole content anymore.
You can either approach this by using a plugin like iScroll within your scroll div to replace the standard functionality or you can make sure that the images fill the whole space regardless of width (by using classic responsive techniques to position the imgs inside a container so that parts of them are cropped of, depending on aspect ratio).

I like solving tricky problems - this was definitely one of them. =)

**Comment by lahmiro** [comment]
Thank you for all the information!! I will revise my CSS code and check iScroll out and test it on iMac again. Thanks again! :)

**Comment by janpaepke** [comment]
so this issue can be considered closed?

**Comment by lahmiro** [comment]
I still have some issues of hiding the scrollbar, but so far I think it's good. Thank you for your help!

**Comment by lahmiro** [comment]
Sorry I think I need to reopen this issue. Now the images look good within the container, but when I scroll them down on iMac, they stopped in unwanted positions for a long time and scrolled down quickly after that.

**Comment by janpaepke** [comment]
Are you still talking about http://lahmiro.github.io/camera/index.html ?
It works fine for me...

**Comment by lahmiro** [comment]
Maybe it was the problem of the mouse in the lab, I think it works fine as well. Thank you!
