### ISSUE TITLE
Pinned element: Trigger 2. animation after 1. is complete

### ISSUE THREAD

**Issue by zlajaa1** [janpaepke/ScrollMagic#245]
Hi,

I would like to produce effect like these:

1. Pin element,
2. Slide in element A form left (to the center),
3. Slide element A to the left (of screen),
4. Slide in element B from the right (to the center),
5. Slide out element B
.
.
. 
10. etc

My problem is next, if I pin element and trigger animation for element A, it start to animate trough some time interval (say it 1 second). But if I trigger animation for element B, without letting animation for element A to complete, element A gets stuck in the middle of animation.

So I want to:
1. Scroll down,
2. Start the animation,
3. If the user continue to scroll
    - either stop animation for element A and start animation for element B
    - or wait for animation a to finish and than trigger animation for element B
 Any solution that will complete animation after animation.

I'm quite new to JS and ScrollMagic plugin so I donno is there any onComplete methods or such.

Thanks

**Comment by janpaepke** [comment]
I hope I understand you correctly.

You have two animations and two scenes.
If the first scene is triggered it should play Animation A and if the second scene is triggered it should play Animation B. If by the end of Animation A the user has not continued scrolling (and thus animation B hasn't been triggered) it should automatically be triggered.

There are many different ways to implement this and they mostly depend on how exactly you want the animations to behave on user input (scrolling backwards/forwards past trigger positions, while animations are running)

One question that arises is: What happens if the user scrolls back past the trigger of Scene2, when Animation A was previously stopped.
Should Scene 1 resume playback from wherever it was previously stopped?
If so it would mean it would still trigger animation B as soon as it's finished.
This could get kinda weird because Animation B would start to be reversed (reverse trigger scene 2) and then be played forward again as Animation A finishes.
To see this in action, check here: http://jsfiddle.net/janpaepke/Ldmdj9p9/

Now this CAN be fixed by defining, that Animation A should not be resumed, when reverse triggering Scene 2: http://jsfiddle.net/janpaepke/Ldmdj9p9/1/

The problem now though is that if we wait for Animation A to play out and Animation B is triggered and we then scroll back to reverse Scene 1, Animation B won't be reversed, because we never passed the trigger of scene 2, which would take care of that.
We could of course add another callback to Scene 1: http://jsfiddle.net/janpaepke/Ldmdj9p9/2/

Now this already looks pretty good. But in the above example B reverses at the same time as A.
What if, on reverse, we want to keep the playback order. That means if B has been played (be it because A is finished or Scene2 has been triggered) and we go backwards, First B should be reversed and THEN A should be reversed.
Maybe we also want to skip Animation A to the end if Scene 2 is triggered before it reached its end naturally.
We can do that too... For example by wrapping them in a timeline and building custom trigger logic like so: http://jsfiddle.net/janpaepke/Ldmdj9p9/3/

Even if in your example you want yet another behavior you should be able to take it from here.

best regards,
J

**Comment by zlajaa1** [comment]
Hi J,
thanks for examples, now i'm curious how to assign all of the tweens to pinned element.

In other words, how to pin whole animation.

Thanks,
Z

**Comment by zlajaa1** [comment]
Hi J,
after some testing and trying to assign similar logic, I was unable to build animation I need, so I;ll try to clear things up a bit.

I want to produce next:
1. Pin scene (which will have around 15 animations inside of it)
2. User trigger 'scene1a'
    - disable scroll (I got script for this, but let me know if plugin provide similar solution)
    - play timeline (which animate couple of elements at the same time), so i think multiple tweens
      here
    - after animation is done enable scroll (is there any onComplete call that plugin provides?) 
3. User trigger 'scene1b'
     - everything is the same, just the elements are leaving the screen now, so the new one from animation in scene2 can come on blank screen.

and step 2 and 3 are repeated untill all 15 animations are done. 

Now i need all of these scenes in pinned element, and triggered to autoplay (no duration assigned to pinned element), and to be played in reverse.

The problem I had is that if I:
1. Scroll down (which will activate trigger)
     -Animation will start
Now fast scroll up, before the animation is complete. Animation will stuck, for example if I was messing with animation of opacity from 0 to 1 it will stuck on 0.7 and it will react on reversed animations only.

Please let me know if you need more details.

Thanks,
Z

**Comment by zlajaa1** [comment]
This is what I wrote ant it work on scroll (as duration is assigned),
//Animate all elements with delays / delay is equal to previous animation time
var elementsAnimation = new TimelineMax().add([

	//First Screen
	TweenMax.to('.ttl1', 1, {opacity: 0}),
	
	//Second screen
	TweenMax.to('.ttl2', 1, {opacity: 1, delay: 1}),
	TweenMax.to('.tablet', 1, {left: 0, delay: 1}),
	TweenMax.to('.laptop', 1, {right: 0, delay: 1}),
		
		TweenMax.to('.ttl2', 1, {opacity:0, delay: 3}),
		TweenMax.to('.tablet', 1, {left: -1000, delay: 3}),
		TweenMax.to('.laptop', 1, {right: -1000, delay: 3}),
	
	//Third screen
	TweenMax.to('.ttl3', 1, {opacity: 1, delay: 5}),
	TweenMax.to('.circle1', 1, {opacity: 1, delay: 5}),
		
		TweenMax.to('.ttl3', 1, {opacity: 0, delay: 7}),
		TweenMax.to('.circle1', 1, {opacity: 0, delay: 7}),
	TweenMax.to('#animated-section', 1, {background: '#fb5e33', delay: 7}),
	//Fourth screen
	TweenMax.to('.ttl4', 1, {opacity: 1, delay: 9}),
	TweenMax.to('.hand', 1, {right: 0, delay: 9}),
		
		TweenMax.to('.ttl4', 1, {opacity: 0, delay: 11}),
		TweenMax.to('.hand', 1, {right: -1000, delay: 11}),
	
	//Fifth screen
	TweenMax.to('.ttl5', 1, {opacity: 1, delay: 13}),
	TweenMax.to('.screen1', 1, {opacity: 0, delay: 13}),
	TweenMax.to('.screen3', 1, {opacity: 0, delay: 15}),
		
		TweenMax.to('.ttl5', 1, {opacity: 0, delay: 15}),	
		
	//Sixth screen
	TweenMax.to('.ttl6', 1, {opacity: 1, delay: 15}),
	TweenMax.to('.img-con1', 1, {opacity: 1, delay: 17}),
	TweenMax.to('.img-con1', 1, {left: 500, delay: 19}),
	TweenMax.to('.screen4a', 1, {opacity: 0, delay: 21}),
	TweenMax.to('.img-con2', 1, {right: 0, delay: 23}),
		
		TweenMax.to('.ttl6', 1, {opacity: 0, delay: 25}),
		TweenMax.to('.img-con2', 1, {opacity: 0, delay: 25}),
	TweenMax.to('#animated-section', 1, {background: '#6ac11d', delay: 23}),	
	//Seventh screen
	TweenMax.to('.ttl7', 1, {opacity: 1, delay: 25}),
	TweenMax.to('.circle2', 1, {opacity: 1, delay: 25}),
	TweenMax.to('.screen4', 1, {opacity: 0, delay: 25}),
		
		TweenMax.to('.ttl7', 1, {opacity: 0, delay: 27}),
		TweenMax.to('.circle2', 1, {opacity: 0, delay: 27}),	
		TweenMax.to('.screen1', 1, {opacity: 1, delay: 27}),	
	
	//Eight screen
	TweenMax.to('.ttl8', 1, {opacity: 1, delay: 29}),
	TweenMax.to('.screen1', 1, {opacity: 1, delay: 29}),
	TweenMax.to('.circle3', 1, {opacity: 1, delay: 29}),
		
		TweenMax.to('.ttl8', 1, {opacity: 0, delay: 31}),
		TweenMax.to('.circle3', 1, {opacity: 0, delay: 31}),
		TweenMax.to('.screen5', 1, {opacity: 0, delay: 31}),
	TweenMax.to('#animated-section', 1, {background: '#ff982a', delay: 29}),
	//Ninth screen
	TweenMax.to('.ttl9', 1, {opacity: 1, delay: 33}),
	TweenMax.to('.screen1', 1, {opacity: 0, delay: 33}),
	TweenMax.to('.circle3', 1, {opacity: 0, delay: 33}),
	TweenMax.to('.circle4', 1, {opacity: 1, delay: 33})
		
]);

//Pin scene and assign elements
var pin = new ScrollScene({
	triggerElement: '#trig-pin', 	// Pin trigger element
	triggerHook: 0,	 				// Trigger distance
	duration: 15000					// Pin duration / Without it it will act as auto-play / With it, it will react only on scroll
	})
	.setPin('#animated-section')	// Set pin to specific element
	.setTween(elementsAnimation)	// Set tween animations for pinned scene
	.addTo(controller);				// Assign pin to controller

});

**Comment by janpaepke** [comment]
Hi!
Sorry for the delayed answer, I was on holidays...

I'm sorry to say that I am still not sure what you are trying to achieve.
It seems to me that you need to simplify it a lot in order to arrive at where you're trying to go.

I would ask you to create your logic as a simplified example in a jsdfiddle, as I did above.
Then we might be able to figure this out together.

**Comment by zlajaa1** [comment]
Hi Jan,
thanks for help, I'll try to make jsFiddle as close as possible. 

Until stay cool, and thanks for plugin

**Comment by janpaepke** [comment]
any updates?

**Comment by zlajaa1** [comment]
Well, yes, but I can't call it a real update :D, as soon as I make sure it's good solution I'll post it

**Comment by janpaepke** [comment]
any updates? ;)

**Comment by zlajaa1** [comment]
Hey Jan,
yes and no. I changed my animation, and after change some solutions cross my mind, but as I work I can't try it. No free time for it :D

**Comment by janpaepke** [comment]
Ok, then I'll close it for now.
If you have time to get into this more, we'll reopen. :)
