### ISSUE TITLE
Crashes Dreamweaver as soon as i open scrollmagic.js

### ISSUE THREAD

**Issue by drnen101** [janpaepke/ScrollMagic#264]
Anyone else having this issue? Since i upgrade to 2.0 dreamweaver crashes immediately as soon as i try to open the included js.
Have been back and forth with Adobe support and they can give no insight.

**Comment by janpaepke** [comment]
Well I guess the obvious answer is that ScrollMagic is just too awesome for Dreamweaver to handle.

But kidding aside it seems to be something in Dreamweaver's code checker and/or highlighter, that is responsible for this.

Here's what I found out:
 1. open a new (empty) javascript file
 2. open ScrollMagic.js with a different editor (i.e. notepad or textedit)
 3. copy and paste all but the last `);` into the empty file.
 4. write `)`.

Boom -> crash.
Well shit.
Let's try again:
 1. open a new (empty) javascript file
 2. open ScrollMagic.js with a different editor (i.e. notepad or textedit)
 3. copy and paste all but the last `);` into the empty file.
 4. scroll to the beginning of the file (using scroll wheel)
 5. click somewhere
 6. scroll back down (using scroll wheel)
 7. click after last `)`
 8. write `)`.

There ya go. no crash. At least sometimes. That makes total sense, right?
What does this tell us?
The obvious answer is that Dreamweaver is one of the worst ways to edit your code. Apart from maybe MS Frontpage (ever used that? ;)).
Again, kidding aside I believe that Dreamweaver tries to process some chunks at once that it just can't.
Who knows why? The JS is definitely valid though...

I strongly recommend a decent editor like [Sublime Text](http://www.sublimetext.com/)
Promised: It hasn't crashed on me a single time. :)

**Comment by drnen101** [comment]
hah thanks for the response. I dont have a good excuse for why I use dreamweaver other than that it's what I started with in college and its just familiar. I'll give sublime a shot ;)

thanks again!

**Comment by janpaepke** [comment]
you'll love it, trust me :)

**Comment by lculver87** [comment]
I had this same problem in dreamweaver CC (but not in CS5). The scrollmagic.js file was linked to all of the pages, and all of the pages of my site crash DW as soon as I open them. My workaround was this:

Rather than including like this:

<script type="text/javascript" src="js/scrollmagic/uncompressed/ScrollMagic.js"></script>

You can try this:

<script type="text/javascript">
document.write('<scr'+'ipt type="text/javascript" src="js/scrollmagic/uncompressed/ScrollMagic.js"></scr'+'ipt>');
</script>

It will still crash for no reason when you open the scrollmagic.js, but it stops Dreamweaver from trying to validate the included file. This prevents the crashes, but I'm not 100% sure it's best practice. 

You shouldn't have to rely on workarounds when dealing with valid code. I've just about had it with Dreamweaver. I would switch editors, but I'm just so familiar with it. It's like an old sock that I can't quite seem to throw away. Sublime looks really interesting. 

ScrollMagic is just too awesome to not use. I've used other similar plugins and I've coded scroll effects myself in my websites, but nothing is smoother than ScrollMagic. Thanks btw.

**Comment by janpaepke** [comment]
thank you for your input!
And also thank you for your kind words!

It's a valid workaround, but as you said - things like makes code harder to read and ultimately very confusing – especially if you work with other people.

So my suggestion is still: try switching to SublimeText. Trust me: After a while you'll wonder how you ever coded with anything else...

**Comment by RobertAllenThompson** [comment]
My Dreamweaver CC 2015 crashes if I link to the local copy of scrollMagic, however If I link to the CDN of scrollMagic it doesn't.
