### ISSUE TITLE
jQuery plugin breaks ScrollMagic 2.0.0

### ISSUE THREAD

**Issue by pngoossens** [janpaepke/ScrollMagic#268]
Hi,

including the 'jquery.ScrollMagic.js' plugin seems to break ScrollMagic 2.0.0. For example, I've use the following HTML markup:
```
<html>
   <head>
       <script src="http://code.jquery.com/jquery-1.11.2.js"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.0/ScrollMagic.js"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.0/plugins/jquery.ScrollMagic.js"></script>
   </head>
    <body>
        ...
    </body>
</html>
```
Typing in `ScrollMagic.version` in Chrome's console yields the following error:
```
Uncaught ReferenceError: ScrollMagic is not defined
```
As soon as I remove the jquery.ScrollMagic.js line from the head of the document, typing in `ScrollMagic.version` correctly returns 2.0.0 as the version. I've also tried the latest 2.x version of jQuery, but the problem persists.

Is this a bug/issue with ScrollMagic/it's jQuery plugin or a PEBCAK?

**Comment by janpaepke** [comment]
Nope, that's totally my fault.
If something is a jQuery plugin it should be available within the jQuery namespace.
That is why when using this plugin ScrollMagic is available using `$.ScrollMagic` (see [here](http://janpaepke.github.io/ScrollMagic/docs/framework.jQuery.html)).
I had some discussions with colleagues wether or not this should mean that the regular browser global (`ScrollMagic`) should be removed.

The consensus was, that it shouldn't. Exactly because of situations like this, where it might cause confusion.
Unfortunately I seem to have forgotten to remove the deletion of the browser global, before releasing 2.0.0.
My bad. :)

This will be fixed for the next version.

In the meantime you can either remove [line 40 of jquery.ScrollMagic.js](https://github.com/janpaepke/ScrollMagic/blob/a23e478c5c20396d9663b704dc92456f2405dda1/scrollmagic/uncompressed/plugins/jquery.ScrollMagic.js#L40) or use $.ScrollMagic instead.

**Comment by pngoossens** [comment]
Commenting out line 40 of jquery.ScrollMagic.js, or even better switching to ScrollMagic 2.0.1, works like a charm! Thanx!

**Comment by janpaepke** [comment]
glad I could help :)

**Comment by bg87** [comment]
I'm using scrollmagic 2.0.3 and this issue is happening.
