### ISSUE TITLE
ScrollMagic triggers twice

### ISSUE THREAD

**Issue by malballah** [janpaepke/ScrollMagic#280]
Hi Jan,

Thanks in advance for your support
the problem is that scrollmagic triggers twice when I append some divs before the trigger element
as the trigger element goes down
and this also happens in your example http://janpaepke.github.io/ScrollMagic/examples/advanced/infinite_scrolling.html
but this happens only in start event not in enter event
regards

**Comment by janpaepke** [comment]
Hi there,
thanks for letting me know.
The current behavior is actually correct, because the `start` event is supposed to trigger when ever you pass the start point of the scene, regardless of direction.
The `enter` event however is only supposed to trigger, when entering the scene.

So you are actually correct, that for this example listening to the `enter` event would be better.
I will change it accordingly.
