### ISSUE TITLE
Scrolling to an element after tween has completed, and resetting

### ISSUE THREAD

**Issue by BenjoJ** [janpaepke/ScrollMagic#284]
Hi Jan, sorry to ask another question

I have created a JSFiddle to help explain what I am trying to do: http://jsfiddle.net/c2gp3y7e/3/

If you view the JSFiddle and scroll all the way down to the bottom of the demo, the slides will come in as you scroll. If you then click the link in screen 3, it should scroll up to screen 2 again. It will still be on slide 6, but I need it to go back to slide 1 when you click the link.

I have successfully reset the tween back to slide 1 in the click function of the link, and when the scroll animation gets up to Screen2 it does show as being on slide 1. The problem is, if you then scroll up, the scroll position is still at the bottom of the pinned Screen2, meaning that the tween animation simply flicks back to the end (the relevant position based on the scroll position) and goes in reverse again, I need to somehow, in the click function, scroll all the way up to the top of the pinned element.

Does that make sense?

Thanks

Ben

**Comment by rubaff** [comment]
First of all: thanks for the great lib, love working with it. I just wanted to post an issue and found this one - the second part of your question ist exactly the problem I'm trying to solve right now (if I understand it right).

I'm resetting scroll via JS and the animation isn't updating correspondingly. Is there a way to refresh it? scene.update() or scene.refresh() didn't seem to work.

**Comment by janpaepke** [comment]
@rubaff I think your issue might be a different one, as this case is quite special. It is related to a case, where a scene is disabled during automated scroll, see here: https://github.com/janpaepke/ScrollMagic/issues/283
Please post your issue seperately, following the [troubleshooting guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#troubleshooting).

@BenjoJ You can achieve this by simply manually setting the scene's progress to 0. using ´Scene.progress(0)´.
This will put the scene back to its initial state, see here: http://jsfiddle.net/c2gp3y7e/6/

Mind that this will also result in the position of the scene being reset to the top, because the pinning position is also different initially.
To avoid this you could define two scenes with the same start and end parameters and use one for animation and one for pinning. Then only reset the one responsible for animation.

__Addon:__
You should check out the ScrollMagic example on [anchor link scrolling](http://janpaepke.github.io/ScrollMagic/examples/advanced/anchor_link_scrolling.html).
There you will learn how to properly implement scroll functionality, as also documented in the [docs](http://janpaepke.github.io/ScrollMagic/docs/ScrollMagic.Controller.html#scrollTo).
The benefit of doing it like this is you could also do something like `controller.scrollTo(PhilosophyScene)` and it would automatically scroll to the beginning of the scene using your custom function (jQuery animate).
I modified the example to account for this: http://jsfiddle.net/c2gp3y7e/7/

I had to do a workaround for the callback, which actually lead me to realize that I should extend the customizability of `.scrollTo` with supplying an additional callback.
I will definitely do this for the next version.

**Comment by BenjoJ** [comment]
Thank you Jan, your reply has been very helpful and has sorted my issue. I have implemented the alternative scrolling method as per your example and it works as expected.

One thing I have noticed, and I don't know if this is a biproduct of the changes I have made, but if you use the scroll function to scroll past #Screen2 down to the #Screen3, it appears that the height of #Screen2 is that of all the slides being stacked on top of eachother. If you scroll down as you would normally, without using the scroll function, then all screens show as the correct height.

I have added a link to the JSFiddle to show you this - look out for the white gap after the red slide as the function scrolls down the page. This is what I need to get rid of.

http://jsfiddle.net/c2gp3y7e/11/ 

If this is a separate issue please let me know and I will raise a separate thread.

Thanks again

Ben

**Comment by BenjoJ** [comment]
Also, I have tested the new scroll function you have suggested on mobile, and it doesn't seem to work. My old method did work, so before I look into it is this something you are aware of?

**Comment by janpaepke** [comment]
Hi Benjo,

the white gap is actually a result of the pinning.
If an element is pinned and `pushFollowers` is true (which it is by default) it will push following elements down, so it doesn't overlap them during pin.
If the pin is disabled you see the "white gap".

This is what I also described in my initial answer:
> Mind that this will also result in the position of the pinned element being reset to the top, because the pinning position is also different initially.
To avoid this you could define two scenes with the same start and end parameters and use one for animation and one for pinning. Then only reset the one responsible for animation.

Check this out: http://jsfiddle.net/c2gp3y7e/12/

As per your mobile troubles: The scrolling method is essentially the same, just the code structure is different.
Make sure this isn't something else causing this...

**Comment by BenjoJ** [comment]
Ah yes, thanks Jan I see how you have accomplished this. I've noticed on your example that the scroll animation appears to pause on screen2 as it continues to scroll down. I understand why this is but as a work around I was wondering if it was possible to temporarily remove the pin when the scroll function is called (to essentially bypass the gap created by pushFollowers), then reapply it once the scroll has completed? 

I did have a look into the mobile issue with the scroll, and noticed that the JSFiddle shows the same issues with mobile as my development site displays. I may look into it in the future but I'm happy to use my original solution for now. 

Thanks again

Ben

**Comment by janpaepke** [comment]
Well theoretically sure. You could remove the pin before scrolling and reapply it afterwards.
But think what that would mean, when scrolling down you would scroll to where scene3 starts, then reenable the pin. suddenly scene3 get's pushed down, because it should scroll into view after the pin.
The total timeline of the site would get longer so to speak.
So the position you scrolled to would be wrong and you'd have to additionally do a jump at the end.
That is kind of very quirky behaviour...

This is where it gets very messy.
Your scroll targets change while modifying the content.
I strongly recommend reconsidering if you truly want this behavior.

If you think so, there are a lot of workarounds to consider.
I updated the fiddle accordingly and changed it back to a custom animation function, as the callback got to be complex to be generally valid.
http://jsfiddle.net/c2gp3y7e/13/

When testing it pay attention what happens to the scrollbar and try to understand what is happening.
Again I would advise against going down this road.

**Comment by janpaepke** [comment]
does this resolve your issue?

**Comment by BenjoJ** [comment]
Hi Jan
I did try implementing the above but I wasn't happy with the usability. The choices ended with two - either have the white gap or have the screen pause as you're auto-scrolling down. I decided to leave it with the white gap as having the screen pause looks like a glitch.

This is the site I am working on: http://timespaceeducation.com.

Thanks

Ben

**Comment by BenjoJ** [comment]
I have removed the ScrollMagic functionality from the site, so please consider this issue closed. Thanks for your support overall.
