### ISSUE TITLE
How to position elements for horizontal cascading pins.

### ISSUE THREAD

**Issue by fniwes** [janpaepke/ScrollMagic#291]
I have two scenes and a element, absolute positioned, that i want to have pinned across the two scenes.

While in first scene is everything all right, just at the moment that the second scene kickoff, the element goes off screen.

Here is a jsfiddle that mimics my setup http://jsfiddle.net/2rmhe9e9/2/

I know there is something wrong with my approach because, a similar setup, but vertical, is not working neither. I guess that the issue is with absolute positioning, but I am not sure and I don't know how to circumvent the issue.

Thanks for your help.

**Comment by janpaepke** [comment]
Hi!
This actually does seem to be a bug, as your implementation is correct.
It might be a bit complicated to solve so in the meantime you can help yourself with this workaround:
http://jsfiddle.net/2rmhe9e9/4/

Essentially instead of positioning the pinned element `absolute` you make a wrapper around it and position it instead.

regards,
J
