### ISSUE TITLE
Page is not scrolling to anchor link id from other page.

### ISSUE THREAD

**Issue by vijay-vanecha** [janpaepke/ScrollMagic#298]
Hi, 

Thanks for Great plugin. 

I have about 6 sections in my website home page. 3 sections have parallax effects. I have given ID's to each sections to scroll to particular section from other page anchor links. My problem is when i am clicking home page sections link from other pages, browser is not scrolling to particular sections. Page scrolls while page is loading but immediately it is scrolling to top of page. This issue is occurred only in firefox. For chrome, safari & IE it is working fine.

I am not sure it is problem related to scrollmagic or not. After i am removeing "tweenmax.js" links are working fine. I also can not remove tweenmax.js because i am using some timeline animation in homepage parallax effect.

Thanks again.

**Comment by janpaepke** [comment]
Hi,
I'm having trouble understanding what you're saying.
please try to clarify and if possible post a link to a demo or screencast.

**Comment by janpaepke** [comment]
I'm closing this until more information is available...

**Comment by herrsauber** [comment]
Hi,

I believe that I'm having the same problem. I'll try to put this simply... I have a link on the index page of my ecommerce store (a href="http://www.store.com/product/productName#details") that is supposed to go to a specific section of a product page (the details section which is way down on the page). Instead of going to that point like it would if ScrollMagic wasn't installed, it goes to the top of the product page. How would I make it go to that specific <a id="details"> section of the site?

I have the scrollTo plugin working. It works for the link that is on that product page, but doesn't on any link outside of that page (on the index page in this example).
