### ISSUE TITLE
Trigger scene on another scenes progress

### ISSUE THREAD

**Issue by omago** [janpaepke/ScrollMagic#305]
Hi Folks,

I would like to be able to trigger scene on another scenes progress, 

I have an element that is pinned, inside this element i have couple of articles that i want to reveal on certain points in pinned elements progress. I am not event sure is this the best approach to this problem. My idea is to stop scrolling (pin the container) and then as user scrolls i would like be able to trigger animations of articles inside this pinned element. The problem is that if element is pinned than i am unable to trigger articles animation because scrolling is disabled for the duration of the containers element scene.

How could i do this?

Best,
Domagoj

**Comment by justinmarsan** [comment]
If I understand correctly, you could still be able to use the scroll position on a container of the pinned element, which is still going te be scroll through...

#container > #pin is pinned

#container > (#pin) > .articles are shown based on #container

I hope that makes sense.

**Comment by janpaepke** [comment]
Hi there!
That's actually a common misconception: Scrolling isn't disabled.
Only the visual representation (the content moving up) is disabled. And that's only because you chose to pin an element with the size of the viewport.
If it was smaller, you would still see the rest of the content moving.

So it is no problem at all to define one scene that does the pinning (for a certain duration) and define different scenes to trigger animations (0 duration).

The only thing that you need to keep in mind is that elements that are inside of the pinned element will not move, during pin.
They only start moving again once the pin is over, which is probably too late for you.
So you can't use them as `triggerElement`.

But that's no problem, as the pin has a definite duration and you can use the offset option to delay animations within the pin phase.

here's an example:
```js
// pin scene
new ScrollMagic.Scene({duration: 1000, triggerElement: "#pinContainer"})
    .setPin("#pinContainer")
    .addTo(controller);

// animation scene
new ScrollMagic.Scene({triggerElement: "#pinContainer", offset: 200})
    .setTween("#animElem", {opacity: 0.5})
    .addTo(controller);
```

This will fade `#animElem` to an opacity of `0.5` exactly 200 pixels after the pin has started.

hope this helps.

J

**Comment by omago** [comment]
Thanks man!

I am aware that scrolling isn't disabled, as you said elements inside pinned element will not move - that is what i meant disabled. 

I will try this, thanks for help!!

**Comment by janpaepke** [comment]
let me know how it goes, and close this issue, if everything is resolved. :)

**Comment by omago** [comment]
This works as expected. Thanks!

**Comment by nimmuks** [comment]
Hi,

Can i add two scenes into one.

i want to setclasstoggle for h2 and h3 into one function.

my example goes here:-

				 // build scene
					 var scene = new ScrollMagic.Scene({triggerElement: "#me"})
						  // trigger animation by adding a css class
							 .setClassToggle("h2", "tweenh2")
					 .addIndicators({name: "1 - add a class"}) // add indicators (requires plugin)
								 .addTo(controller);
							 
                               // build scene
					 var scene = new ScrollMagic.Scene({triggerElement: "#me"})
						 // trigger animation by adding a css class
						  .setClassToggle("h3", "tweenh3")
						 .addIndicators({name: "1 - add a class"}) // add indicators (requires plugin)
						 .addTo(controller);

Please save me.... :)
