### ISSUE TITLE
TweenMax scrollTo triggered on Element

### ISSUE THREAD

**Issue by omago** [janpaepke/ScrollMagic#308]
Hi,

I have a problem. 

Is it possible to trigger scrollTo animation with scrolling, something like this:

```js
    // pin partners element
    new ScrollMagic.Scene({
        triggerElement: "#partners",
        offset: scene_height,
        duration: 0,
        triggerHook : 0
    })
    .setTween(TweenMax.to(window, 2, {scrollTo:{y:values_offset, autoKill:false}}))
    .addIndicators() // add indicators (requires plugin)
    .addTo(controller)
```

Above code doesn't work.

The idea is that after scrolling is finished on one section user jumps to next section.

Thanks!

**Comment by janpaepke** [comment]
Possible yes, recommended no.

The reason the above code doesn't work is because the animation is different every time, as the start position can vary.
So you need to trigger a new one every time.

You do that like this:
```js
    new ScrollMagic.Scene({
        triggerElement: "#partners",
        offset: scene_height,
        duration: 0,
        triggerHook : 0
    })
    .on("enter", function () {
        TweenMax.to(window, 2, {scrollTo:{y:values_offset, autoKill:false}})
    })
    .addIndicators() // add indicators (requires plugin)
    .addTo(controller)
```

The reason I wouldn't recommend this is that this is considered scrolljacking and imho very bad UX.
ScrollMagic is great, because you allow users to control the "playback speed" and direction of your content. If you use automated scroll you take this control away from him.
So my recommendation is don't do that! Leave the user in control! Find better ways of getting him to do what you want, like indicators telling him to keep scrolling (which most users do anyway).

**Comment by omago** [comment]
Thanks Jan,

This works. I would not consider this as a scrolljacking because i have a couple of scenes that are set to viewport height. When users scrolls trough the content on one scene he is than taken to another scene. It is more like a presentation feel.

**Comment by janpaepke** [comment]
Well it's your decision :)
In my opinion the only situation that warrants the use of automated scroll is navigation (i.e. the user clicks on an in-page-link).
But you know - that's just me. :)

**Comment by janpaepke** [comment]
P.S.: Instead of using the mouse wheel try dragging the scrollbar past your trigger point and you'll see why I don't like it. :)

**Comment by omago** [comment]
I see what you mean. 
I am still new to this scrolling thing so i am still experimenting :), we will se what works best. My goal is to make everything as i imagined and then optimise.

Thanks for the help!!!

**Comment by janpaepke** [comment]
you're welcome. :)
