### ISSUE TITLE
section wipes content height issue.

### ISSUE THREAD

**Issue by jon21021985** [janpaepke/ScrollMagic#333]
Hello,

I am using the section_wipes_natural.html example, is there a way to make sections that are larger than the browser height scroll?

If you have content that is larger than the browser window it is cut off because the section is fixed.

This site allow the content to scroll before moving to the next section:
http://work.antonandirene.com/karimrashid/

Thank you all in advance.
Jon.

**Comment by janpaepke** [comment]
Hi Jon,

the way you do this is by creating a tween that moves the content of the fixed section upwards and attach it to a scene that runs while scrolling through it.
This way you sort of replace the natural scrolling, which is exactly what's happening on your example page.

Hope this helps?

**Comment by simon88pl** [comment]
@janpaepke could you give any example? 

Thanks in advance.
Simon

**Comment by janpaepke** [comment]
Sure,
Here's an example: http://jsfiddle.net/Lt97jt7k/

**Comment by jon21021985** [comment]
Hi Jan,

This is fantastic! Thanks for the help.

Jon

**Comment by simon88pl** [comment]
Hi Jan,

thank you for your help! This is an idea, but not without problems:

What about different screen resolutions? The amount of "aditional content" may vary. It would be better to automated it / depends on all content in the slide. It is possible?

http://jsfiddle.net/Lt97jt7k/2/ - here I have removed < b > in turqoise slide and I have empty slide and the content after it. Even if it is not removed you have small content (word "two") on empty slide and next other content.

Thanks,
Simon

**Comment by jon21021985** [comment]
I have been playing with the example, Im close but have a few issues...

http://jsfiddle.net/st86x71m/

I need to prevent the gap after the additional content, so the next panel scrolls into view when the bottom of the additional content is at the bottom of its parent.

also is there a way to dynamically set the z-index?

any help is appreciated.

Thanks
Jon

**Comment by simon88pl** [comment]
@jon21021985 it still based on manual settings (ex. duration), not automatic on content size and screen resolution. I still looking for solutions on JavaScript side. @janpaepke do you have any idea?

**Comment by simon88pl** [comment]
@janpaepke I do not want to make a mess in issues, so I write here once again.

Thank you for help with navigation (https://github.com/janpaepke/ScrollMagic/issues/339), it works fine. Unfortunately I still have problem with content height. Please look at this example - http://jsfiddle.net/pra8gta0/1/ which is more "real-life", more like real, typical one-page website. My goal is to make on this type of page nice animations instead standard scrolling, like section wipes in your plugin (this effect looks amazing).

The problem is that I don't know which content is main and additional, and I want to have transition for all slide, not separately for main and additional. For smaller screens window height is small and the greater part of content is invisible.

Do you have any ideas?

**Comment by sandovalg** [comment]
@jon21021985 on the jsfiddle you provided with the z-elements http://jsfiddle.net/st86x71m/3/ were you able to have this working with a *wipe over* versus the present wipe under? Please advise. Thanks for you contribution! Look forward to a response.

**Comment by MichaelCalleia** [comment]
Know this is closed, but @sandovalg and @jon21021985  have a look at http://jsfiddle.net/michaelcalleia/muha5ptL/

It replicates the example in the original post fairly closely. Since % are used, panel sizes should recalulate when the screen is resized, but there is a delay when you do so in jsfiddle.

**Comment by jon21021985** [comment]
@MichaelCalleia this looks good! how would you create the overlays for the panels that are below? In the example the panels that are below have an overlay which fades out to 0 as you scroll.

**Comment by MichaelCalleia** [comment]
@jon21021985 finally got that working too: https://jsfiddle.net/michaelcalleia/jjuj25wb/17/

On JSFiddle there is something funky about the scroll bars, but they are working better here: humanist.co (no garentee this example will not change in the future).

**Comment by MichaelCalleia** [comment]
@jon21021985 See https://jsfiddle.net/michaelcalleia/k85qg9gu/ this looks like the orginal.

**Comment by ergum** [comment]
Hi all! Nice code. I'm trying to use it but when I want to **add objects inside the slides** and apply some effect like a parallax, why the indicators of that object and the own objects **gets jittering** all the time?

I couldn't get a smooth animation anyway, here is the example https://jsfiddle.net/joseluisgj/vwdjn5hd/5/ (Inside Panel 4)

Any idea? Thanks !

**Comment by gtkumar2020** [comment]
How to add an additional section in scrollmagic
