### ISSUE TITLE
Can offset be set as a percentage?

### ISSUE THREAD

**Issue by kodama78** [janpaepke/ScrollMagic#337]
Hi, I was just wondering if offset in the trigger elements could be set with an offset set to a percentage rather than a hard pixel number.

**Comment by janpaepke** [comment]
No they can't for performance reasons.
Also because the logic of understanding where the trigger position will end up being would become even more complicated than it already is.
Consider using a different `triggerHook` for the scene, which is relative to the viewport anyway.
Or offsetting your `triggerElement` accordingly.

**Comment by ADTC** [comment]
Instead of using `offset` with a fixed pixel value, if you want percentage, just set it as a number in `triggerHook` (no `offset` required). The percentage of viewport height is measured from the top of the viewport.

    triggerHook: 0.05 // i.e. 5% 
    triggerHook: 0.75 // i.e. 75%
    triggerHook: 0.9 // i.e. 90%

`onEnter`, `onLeave` and `onCenter` are merely string aliases for `1`, `0`, and `0.5` respectively.
