### ISSUE TITLE
Scroll jitter on IE and Safari

### ISSUE THREAD

**Issue by arkwis** [janpaepke/ScrollMagic#341]
I have read through a number of issues concerning this, but have not been able to find any solutions (upgrading to 2.0.5 and using transforms did not help). The effects work fine in Chrome and FF, but IE and Safari have visible jitters.

I created a simple demo, which shows the exact behavior on IE10 Win7 and Safari 8 Yosemite. 

http://codepen.io/anon/pen/LVLXvQ

Any help would be very appreciated.

**Comment by janpaepke** [comment]
Hi Arkwis,

this has actually to do with how Safari and IE repaint the content.
Moving elements (that are in content flow) in the same axis as the scroll makes this particularly apparent.
This problem is the reason that for Pins you can't just animate elements in the opposite direction to the scroll (which would make a lot of things easier).

A workaround is to take these elements out of DOM-Flow for their animation.
This can be done by pinning them.

This Pen has the same visual outcome, but uses a PIN to avoid the flickering in Safari: http://codepen.io/janpaepke/pen/WvEPXZ

hope this helps.
J

**Comment by karneaud** [comment]
Hi @janpaepke ,

I'm having the same issue as @arkwis but I'm not sure I follow your workaround. You are saying that we need to

> take the element out of the *dom-flow* to animate them

but isn't that what *pinning* does?

and if I am to understand your logic using this example

html 
```
html
--> body
   --> container
           --> section
           --> section
```
scss
```
html, body {
width:100%;
height:100%;

}

.container {
position:relative;
.section {
position:absolute; // take the dom element out the flow because I need to pin them
}
}
```

js

```
foreach .section

new ScrollMagic.Scene('.section').setPin(section);
```

is this what you're saying?
