### ISSUE TITLE
Pause whole tween for x pixel scrolling

### ISSUE THREAD

**Issue by thomasflad** [janpaepke/ScrollMagic#349]
Hi, i'm working on a path animation. This is my current work:
http://codepen.io/thomasflad/pen/oXGdJM

Now, I want to pause the animation at a certain point and for x pixel scrolling. I tried with adding .addPause() to the Timeline but I don't know how to resume the animation.

I am grateful for a tip.

**Comment by thomasflad** [comment]
I've updated my codepen and added this:

    var pathScene = new ScrollMagic.Scene({
		offset: 588,
		duration: 300,
		reverse: false
	})
    .addIndicators()
    .addTo(controller)
    .on('enter', function(e) {
      tlPath.pause();
    })
    .on('end', function(e) {
      tlPath.play();
    });

My problem is that on the end of the pause the path-animation should resume at the last position. Any idea?

PS.: Thanks for your great work!

**Comment by janpaepke** [comment]
Hi Thomas
your solution is quite creative, but unfortunately and evidently it doesn't work.
The reason is that when a scene controls the playback of a tween it can't be paused, because technically it's not even playing - the scene just scrubs it.
So the second scene you added has no effect.

You basically have two possible ways to approach this:
Create two scenes for each part of the animation. This way you could offset the second scene a bit from the end of the first. It would start a bit later and thus the tween would be paused.

The second one is split up the animation in two tweens and then offset those inside a timeline using a delay.
Both require splitting up your bezier curve into two parts.

Since you already set up a timeline I updated your example using the second approach: http://codepen.io/janpaepke/pen/xGjxEY?editors=101

I also set the easing to linear, to account for the fact that scrolling is linear, too and my guess was that you want to keep the red square in view.

_Hint:_ When adding tweens as an array they are added at the same point in time and you don't have to supply an insert time parameter.
