### ISSUE TITLE
Issue with Tween*.set()

### ISSUE THREAD

**Issue by Lynesth** [janpaepke/ScrollMagic#352]
Hey there,

When I use the set() function, the value gets set immediately instead of when the tween should start.
If it's a timeline, it only happens with the sets() at position 0.

To make myself clearer, if I do this :
```javascript
var controller = new ScrollMagic.Controller();
var timeline = new TimelineMax().set("#myDiv", {css:{zIndex: 1}}).to("#myDiv", 1, {x: 100});
var scene = new ScrollMagic.Scene({offset: 1000, duration: 1000, triggerHook: 1}).setTween(timeline).addTo(controller);
```

Then myDiv gets a z-index of 1 as soon as the script is executed instead of when the timeline starts.

I'm not sure I made myself clear enough, feel free to tell me if so.

Regards,

Lyn.

**Comment by janpaepke** [comment]
Hi Lyn,
This is expected behavior, because the `.set` method is written in a way that it doesn't return a tween instance, but just immediately does what it says (it sets a value) as soon as it's called.

This may have been changed in current GSAP versions, so make sure you run the latest version.
Another workaround is to just add a `.to` tween with a duration of `0.00001`.

regards,
J
