### ISSUE TITLE
Scene update() not working as expected.

### ISSUE THREAD

**Issue by hatchbee** [janpaepke/ScrollMagic#353]
Hello @janpaepke , 

I am using ScrollMagic for my current project, boy is it seamless! Although, I am stuck on something..hope if you can help me on it.

Here is the issue--

I am using ``jquery load()`` to load/append a html into a ``'scene'``. once the html is loaded I am calling ``scene.update(true)`` to update the scene's start and end position, since the height and width of the scene changed after jquery load.

Here is the small snippet of the code,
```js
var accessoryScene = new ScrollMagic.Scene({
			triggerElement: $(".mainTabs[data-section='accessories']")[0],
			duration: getOuterHeight(".mainTabs[data-section='accessories']")
		})
		.setClassToggle("[data-sectiontab='accessories']","active")
		.addTo(sectionCtrl);

    $("#accessories").load(url,function(){
            accessoryScene.update(); // <-- NOT WORKING, even tried refresh(),update(true)       
    })

```

But, nothing does changes, start and end position are the same as before scene was loaded.. 

Am I doing correct? How can I update Scene's start,end,duration and offset ??

 Thanks!

**Comment by janpaepke** [comment]
Hi!
You are indeed misinterpreting what `.update` does.
All it's supposed to do is update the current playhead of the scene to the current position.
This is usually done automatically (for example on scroll) and there are very rare cases where you would need to call it manually (As mentioned in the docs).

Your issue is a different one:
The start position of the scene should be updated automatically, when the triggerElement moves.
But my guess it doesn't as you said you are inserting content "inside" of the scene.
So what changes is the end. And the end is defined by the scene's duration.

Now if you have a look at how your scene's duration is defined, you'll see `getOuterHeight(".mainTabs[data-section='accessories']")`, which is evaluated to a number, when the scene is created.

If you want the duration to be updated, when you load new content you'll have to supply the (current) height again:
```js
    $("#accessories").load(url,function(){
            accessoryScene.duration(getOuterHeight(".mainTabs[data-section='accessories']"));
    })
```

makes sense, right? :)

_Hint:_ If you include the ScrollMagic jQuery extension you can make use of the advanced jquery selectors and either supply jQuery objects or use selectors directly.
