### ISSUE TITLE
ScrollMagic and Zurb Foundation Topbar

### ISSUE THREAD

**Issue by derfladi** [janpaepke/ScrollMagic#37]
Hi!

just found ScrollMagic and testing it. I have a page based on Foundation. I start simple and try to make my main-navigation sticky (pin it) on the top of the screen after a header-space is scrolled out of view.

However the javascript seems to work but the pin-spacer seems to have wrong calculations (perhaps similar issues as with bootstrap). The div with my navigation shrinks as soon as it is pinned.

Of course I'm using latest version. 

If have prepared a small demonstration with simplified markup. http://jsfiddle.net/2KeRS/14/ (for better results make sure your browser is wide enough to not show the mobile-version). Use http://fiddle.jshell.net/2KeRS/14/show/# to only show the result-frame (easier to debug).

Any ideas what to do?

Thx and best regards
Tim

**Comment by silverbackis** [comment]
Hi Jan. This problem seems to have reappeared in the version 2.0.5 perhaps? I've got an example here. Start the window at a fairly narrow width, scroll a touch, widen the window and the pin wrapper stays the correct size but the child remains with the fixed pixel width.
http://www.healthcaretest.org/

Am I doing something wrong here?

**Comment by silverbackis** [comment]
Sorry, I've just noticed on your ScrollMagic website, with v2.0.5 I believe, the issue is back on the first pinned section, so I assume this isn't an error in my code. I'll use the '!important' workaround for now, and maybe have a quick look to see if I can spot where the code needs to be modified to make this work again.

Thanks.

**Comment by janpaepke** [comment]
Yup, it seems to be back, see here: https://github.com/janpaepke/ScrollMagic/issues/312

**Comment by silverbackis** [comment]
Thanks for the quick response, I'll comment in there if I have anything to add. Apart from this, loving the code, great stuff.
