### ISSUE TITLE
Responsive Offset

### ISSUE THREAD

**Issue by MattOliver7** [janpaepke/ScrollMagic#471]
Hi - Great plugin, it has helped me out massively in achieving the results the client required, thank you. One thing I am trying to conquer now is the responsive side of things. Duration is fine, and the whole thing resizes into a the viewport :)

The problem is the 'offset' of everything as it begins to pin to the top of my page on a mobile. How can I control the position of all my scenes so it fits in the viewport at all screen 
resolutions?

**Comment by madmalta** [comment]
Did you find any solution to this? 👍

**Comment by mattjbrent** [comment]
Hey @MattOliver7  and @madmalta basically the short answer is don't use offset for positioning. I use it for slight adjustments that I set using JS media queries but because of the vast difference of sizing between a large screen and mobile its very unpractical. The reason why they didn't use percentage for offset is because of performance reasons. read the source from Jan [here](https://github.com/janpaepke/ScrollMagic/issues/337) 

The answer is to absolutely position a column of divs that span the height of your whole website you can see an example [here](http://scrollmagic.io/examples/advanced/section_slides_manual.html) if you open up your dev tools and look towards the bottom of the markup you'll see a div that spans the whole height of the website.

you then use this as a container to hold multiple divs that are stacked ontop of each other that you then use as your triggers for your animations. because these are all responsive divs set to a percentage of the height of your browser. 

Fine tuning your animation triggers becomes very easy and precise. Although i'd change alot about this website now, you'll find another example of this [here](http://cosafety.ca/) that is quite complex visually with a lot of animations. This technique enabled me to have precise responsive triggering. (although scroll magic is turned off for mobile so make sure your browser is big enough.

if you view the source again and checkout the #triggers div you'll see what im getting at.

Let me know if that makes sense.
